feat(form): added field groups
patternfly/patternfly pull request #3654
Opened 2020-11-10 15:19 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/3557

2020-11-10 15:22 UTC, patternfly-build commented
Preview: https://patternfly-pr-3654.surge.sh

2020-11-10 18:53 UTC, mcarrano reviewed
Expandable groups look good @mcoker . For the non-expandable field groups I would still expect you to be able to create some hierarchy by indenting child groups even when you remove the expansion. Was that also your intent @lboehling ?

2020-11-11 15:24 UTC, christiemolloy requested changes

2020-11-11 15:24 UTC, christiemolloy commented
is this how you would expect these to overflow or should they truncate ?

<img width="761" alt="Screen Shot 2020-11-11 at 10 17 07 AM" src="https://user-images.githubusercontent.com/20118816/98830150-0fe5f880-2408-11eb-936a-2da7271280c6.png">

2020-11-11 15:25 UTC, christiemolloy commented
Should the Field Groups here have a border between them like the other field groups?

<img width="720" alt="Screen Shot 2020-11-11 at 10 24 08 AM" src="https://user-images.githubusercontent.com/20118816/98830196-1f654180-2408-11eb-9e01-fdae833aa3f1.png">

2020-11-11 15:25 UTC, mcoker commented on src/patternfly/components/Form/form-field-group-header-actions.hbs
> +<div class="pf-c-form__field-group-header-actions{{#if form-field-group-header-actions--modifier}} {{form-field-group-header-actions--modifier}}{{/if}}"
You could, think we could leave it open to add an action group, just a list of actions (like I have here), an overflow menu, etc.

2020-11-11 15:27 UTC, mcoker commented on src/patternfly/components/Form/form.scss
> +.pf-c-form__field-group-toggle {
It's so that the toggle can have it's own layout in the grid so that we can have

```
toggle | header stuff
empty  | field group contents
```

2020-11-11 15:28 UTC, mcoker commented
> Should the Field Groups here have a border between them like the other field groups?

Nope, these are non-repeatable field groups. The ones with a border defined between them are repeatable (`.pf-m-repeatable`)

2020-11-11 15:30 UTC, mcoker commented
> is this how you would expect these to overflow or should they truncate ?

@christiemolloy are you referring to the descriptions or actions, or both? I would expect the description to wrap like that. Maybe not the actions though... maybe that gets `white-space: nowrap;`?

2020-11-11 20:05 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +  {{#> form-group form-group--id="-label2"}}
```suggestion
  {{#> form-group form-group--id="-form-group1-label2"}}
```

2020-11-11 20:05 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +  {{#> form-group form-group--id="-label1"}}
```suggestion
  {{#> form-group form-group--id="-form-group2-label1"}}
```

2020-11-11 20:05 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +  {{#> form-group form-group--id="-label2"}}
```suggestion
  {{#> form-group form-group--id="-form-group3-label2"}}
```

2020-11-11 20:05 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +  {{#> form-group form-group--id="-label1"}}
```suggestion
  {{#> form-group form-group--id="-form-group1-label1"}}
```

2020-11-11 20:05 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +  {{#> form-group form-group--id="-label2"}}
```suggestion
  {{#> form-group form-group--id="-form-group2-label2"}}
```

2020-11-11 20:05 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +  {{#> form-group form-group--id="-label1"}}
```suggestion
  {{#> form-group form-group--id="-form-group3-label1"}}
```

2020-11-11 20:05 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +  {{#> form-group form-group--id="-label2"}}
```suggestion
  {{#> form-group form-group--id="-form-group4-label2"}}
```

2020-11-11 20:14 UTC, mattnolting reviewed
I think you could stack the header on smaller viewports and set `.pf-c-form__field-group-header-actions` to `nowrap`. 

<img width="703" alt="Screen Shot 2020-11-11 at 3 09 31 PM" src="https://user-images.githubusercontent.com/5385435/98859558-60714c00-2430-11eb-824a-b60459afaa20.png">

<img width="1091" alt="Screen Shot 2020-11-11 at 3 06 31 PM" src="https://user-images.githubusercontent.com/5385435/98859703-90205400-2430-11eb-9aeb-0dece9795be0.png">

<img width="593" alt="Screen Shot 2020-11-11 at 2 00 07 PM" src="https://user-images.githubusercontent.com/5385435/98859704-90b8ea80-2430-11eb-9beb-e96aec69ef4e.png">

2020-11-11 22:22 UTC, lboehling commented
> For the non-expandable field groups I would still expect you to be able to create some hierarchy by indenting child groups even when you remove the expansion. Was that also your intent @lboehling ?

I agree with @mcarrano now that I'm looking at this again. Probably would want some indentation/cleaned up padding to make sure the non-expanded groups still have some hierarchy.  I'm also wondering now if my initial logic for the divider lines is holding up when there is a combo of expandable/non-expandable groups and repeating/non-repeating groups. It might be helpful if we divide these examples into more distinct sections, and then possibly have a demo or two showing them all together? 

on a smaller note... changing the button text from "Add parameter" to "Add group" might make the repeating field set example more clear.


@mcoker @mcarrano

2020-11-11 22:37 UTC, mcoker commented
@lboehling sounds good, thanks for the review!

> It might be helpful if we divide these examples into more distinct sections, and then possibly have a demo or two showing them all together?

Yeah, apologies for the example in this PR - that was really just to put all of the functionality out there for review and see how it all looks together. Before releasing, we'll clean up the examples so they're more consumable.

2020-11-11 23:08 UTC, christiemolloy approved these changes
LGTM once you update the actions wrapping

2020-11-23 23:47 UTC, mcoker commented
@christiemolloy @mattnolting @mcarrano @lboehling @mceledonia updated with Lucia's latest design.

Main points are:

* Border under top-level group title/toggle, and between nested groups, spans the full width
* Always a border between nested groups (no longer based on being repeatable)
* Top-level non-expandable group contents is indented, but nested non-expandable groups are not

2020-12-02 02:03 UTC, mcoker commented
@lboehling updated the spacing so that if a non-expandable nested group contains a non-expandable group, that whole group (the title and group contents) is indented. Here's a screenshot of a really complex example to show what it would look like

<img width="1336" alt="Screen Shot 2020-12-01 at 7 44 02 PM" src="https://user-images.githubusercontent.com/35148959/100818670-38ae4c00-3410-11eb-96f6-c55c56516485.png">

2020-12-02 18:14 UTC, lboehling approved these changes
Looks good @mcoker! Thank you!!

2020-12-02 18:32 UTC, mcoker commented on src/patternfly/components/Form/form.scss
> +  --pf-c-form__field-group--GridTemplateColumns--toggle: calc(var(--pf-global--spacer--md) * 2 + var(--pf-c-form__field-group-toggle-icon--MinWidth) + var(--pf-global--spacer--xs));
updated

2020-12-02 19:39 UTC, mattnolting commented on src/patternfly/components/Form/form.scss
> +  grid-row: 2 / 3;
```suggestion
```
I'd remove this, as it would allow multiple bodies and their auto-placement would be 2, 3, 4, etc

2020-12-02 19:39 UTC, mattnolting commented on src/patternfly/components/Form/form.scss
> +  grid-template-rows: auto auto;
```suggestion
```
Don't need this as it's the default

2020-12-02 20:13 UTC, mattnolting approved these changes
Beautiful 🤩 !!!

2020-12-02 22:29 UTC, mcarrano approved these changes
Looks great. Nailed it!

2020-12-02 22:41 UTC, christiemolloy approved these changes
This looks spectacular!!!! thanks for making all those changes

2020-12-02 22:46 UTC, merged

2020-12-02 23:01 UTC, redallen commented
:tada: This PR is included in version 4.69.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.69.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.69.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: