fix(drawer): added light-200 variation for grey background
patternfly/patternfly pull request #3819
Opened 2021-01-28 22:13 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/3813

@mcarrano @mceledonia I added this variation as `pf-m-light-200`. I'd like to be consistent as we use a variation like this going forward. Our page sections are `--pf-global--BackgroundColor-200` by default, and we use `pf-m-light` as the variation name to turn it white, so we have that precedent to work with. I'm thinking we can keep `pf-m-light` to represent white/`--pf-global--BackgroundColor-100`, and use `pf-m-light-200` for `--pf-global--BackgroundColor-200`. That will also allow us to apply this to other components in the same way. Sound OK?

2021-01-28 22:16 UTC, patternfly-build commented
Preview: https://patternfly-pr-3819.surge.sh

2021-01-29 14:53 UTC, mcarrano requested changes
@mcoker I don't have a strong feeling about the naming so I'm good with your approach.

I'm wondering if we can change this example. The specific ask was to have an inline gray drawer panel with a white content area. See the mock here: https://github.com/patternfly/patternfly/issues/3813 Could we create an example that is closer to this? It's the way I see this being used. Thanks.

2021-02-08 17:22 UTC, mcoker commented
@mcarrano updated

2021-02-08 21:46 UTC, mcarrano approved these changes
Looks great @mcoker

2021-02-09 13:52 UTC, mattnolting approved these changes
Beautiful!! LPTM 🌮

2021-02-09 23:38 UTC, merged

2021-02-09 23:47 UTC, redallen commented
:tada: This PR is included in version 4.82.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.82.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.82.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: