Feat tree table issue
patternfly/patternfly pull request #3943
Opened 2021-03-22 15:48 UTC by mattnolting

closes #3900

2021-03-22 15:52 UTC, patternfly-build commented
Preview: https://patternfly-pr-3943.surge.sh

2021-03-23 17:38 UTC, mattnolting commented
@mcarrano @mceledonia @mcoker the responsive state is built in to the examples, so you'll just need to shrink your viewport width to see the implementation

2021-03-25 20:34 UTC, mattnolting commented
@mceledonia @mcarrano updated

2021-03-25 21:05 UTC, mcarrano approved these changes
I like it. Great work @mattnolting . In fact I wonder it we should have used this approach to collapsing row details for all tables on mobile.

2021-04-05 20:48 UTC, nicolethoen commented
How's this going, @mattnolting

2021-04-06 20:06 UTC, mattnolting commented
> How's this going, @mattnolting

@nicolethoen It's in a finished state, just waiting for reviews.

2021-04-06 20:20 UTC, mcoker commented on src/patternfly/components/Table/table-tree-view.scss
> +      margin-top: var(--pf-c-table__toggle--c-button--MarginTop);
Typically we would style `.pf-c-table__tree-view-details-toggle` if we know there will always be an action here.

2021-04-06 20:26 UTC, mcoker commented on src/patternfly/components/Table/table-details-toggle-icon.hbs
> +<div class="pf-c-table__details-toggle-icon{{#if table-details-toggle-icon--modifier}} {{table-details-toggle-icon--modifier}}{{/if}}"
needs to be a `<span>`

2021-04-06 20:26 UTC, mcoker commented on src/patternfly/components/Table/table-tr.hbs
> +  {{~#if table-tr--details--IsExpanded}} pf-m-treeview-details-expanded{{/if}}
should this be `tree-view`?

```suggestion
  {{~#if table-tr--details--IsExpanded}} pf-m-tree-view-details-expanded{{/if}}
```

2021-04-06 20:28 UTC, mcoker commented on src/patternfly/components/Table/table-tree-view.scss
> +  --pf-c-table--pf-m-tree-view-mobile--tr--OutlineOffset: calc(-1 * var(--pf-global--spacer--xs));
should any `pf-c-table--pf-m-tree-view-mobile` var be `pf-c-table--pf-m-tree-view-grid`?

2021-04-06 20:29 UTC, mcoker commented on src/patternfly/components/Table/table-tree-view.scss
> +  --pf-c-table--pf-m-tree-view-mobile--tr--before--BorderColor: var(--pf-global--BorderColor--100);
doesn't look like this is used

2021-04-06 20:29 UTC, mcoker commented on src/patternfly/components/Table/table-tree-view.scss
> +  --pf-c-table--pf-m-tree-view-mobile--tr--before--BorderBottomWidth: var(--pf-global--BorderWidth--sm);
not used

2021-04-06 20:43 UTC, mcoker commented on src/patternfly/components/Table/examples/Table.md
> +| `.pf-c-table__tree-view-content` | `<div>` | Initiates a tree view table content element. **Required with tree view** |
I might swap `-content` and `-main`? I'm not sure if we have both `-content` and `-main` in another component, but typically `-main` wraps the title and whatever may go beside it in an item (eg, menu item, tree view/dual list selector node). WDYT?

2021-04-06 20:44 UTC, mcoker requested changes
Looks great! Just a handful of comments.

2021-04-07 17:23 UTC, mcoker requested changes
Do you need these styles for `__tree-view-content`? 

https://github.com/patternfly/patternfly/blob/5500d9d243f4df92e64ca99aa8a941b40d6699d1/src/patternfly/components/Table/table-tree-view.scss#L73-L75

2021-04-07 17:23 UTC, mcoker commented on src/patternfly/components/Table/table-tree-view-details-toggle.hbs
> +  <button class="pf-c-button pf-m-plain{{#if table-tr--details--IsExpanded}} pf-m-expanded{{/if}}" {{#if table-td--button--attribute}}{{{table-td--button--attribute}}}{{/if}} {{#if table-tr--details-
```suggestion
  <button class="pf-c-button pf-m-plain{{#if table-tr--details--IsExpanded}} pf-m-expanded{{/if}}" {{#if table-td--button--attribute}}{{{table-td--button--attribute}}}{{/if}} {{#if table-tr--details--IsExpanded}}aria-expanded="true"{{/if}} type="button">
```

2021-04-08 12:33 UTC, mattnolting commented
@mcoker updated

2021-04-08 15:19 UTC, mcoker approved these changes
L🍕TM!!! Great work!! 🥳

2021-04-08 15:20 UTC, merged

2021-04-08 15:39 UTC, redallen commented
:tada: This PR is included in version 4.97.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.97.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.97.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: