refactor(log-viewer): removed hover, added scroller
patternfly/patternfly pull request #4042
Opened 2021-05-05 12:17 UTC by mattnolting

closes #4040 

* Removes hover style
* Adds `scroll-container`
* Uses generated html from React PR

2021-05-05 12:21 UTC, patternfly-build commented
Preview: https://patternfly-pr-4042.surge.sh

2021-05-05 12:22 UTC, mattnolting commented
@arivepr This is the structure

``` 
.pf-c-log-viewer(optional pf-m-line-numbers)
  .pf-c-log-viewer__header
  .pf-c-log-viewer__main
    .pf-c-log-viewer__scroll-container
      .pf-c-log-viewer__list
        .pf-c-log-viewer__list-item
          .pf-c-log-viewer__index (line number)
          .pf-c-log-viewer__text (line text, timestamp can be wrapped in a <b> tag)
```

2021-05-05 13:32 UTC, mcarrano requested changes
Thanks for making these changes @mattnolting . Just a couple of visual things I'd like to address:

![Screen Shot 2021-05-05 at 9 28 08 AM](https://user-images.githubusercontent.com/6619860/117148750-87c42880-ad84-11eb-8908-cfea481b52f5.png)


1. Can the spacing in the log window be adjusted? I feel like there is too much space left to the numbers on the left and between entries. If this can be changed I can give you a spacing spec.
2. If Find highlights a line the wraps to multiple lines, I expect the highlight to enclose the entire entry, not just the first line.

2021-05-05 13:49 UTC, mattnolting commented
@mcarrano
> * Can the spacing in the log window be adjusted? I feel like there is too much space left to the numbers on the left and between entries. If this can be changed I can give you a spacing spec.
Sure, just lmk the how so
> * If Find highlights a line the wraps to multiple lines, I expect the highlight to enclose the entire entry, not just the first line.
I don't have any control over that, so unfortunately I can't change it

2021-05-06 20:31 UTC, merged

2021-05-06 22:11 UTC, patternfly-build commented
:tada: This PR is included in version 4.103.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.103.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.103.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: