fix(card): updated support for right aligned
patternfly/patternfly pull request #4045
Opened 2021-05-05 13:33 UTC by mattnolting

closes #4044 
closes #3924

2021-05-05 13:37 UTC, evwilkin commented
👀  watching for https://github.com/patternfly/patternfly-react/pull/5723#pullrequestreview-649247293

2021-05-05 13:38 UTC, patternfly-build commented
Preview: https://patternfly-pr-4045.surge.sh

2021-05-05 15:38 UTC, mcoker requested changes

2021-05-05 15:38 UTC, mcoker commented on src/patternfly/components/Card/card.scss
> +  .pf-c-dropdown {
I think moving the margin that offsets the alignment from the actions container to an individual component is going to cause inconsistencies. You could use other plain things here, too - button, options menu, etc, and then the alignment would be different.

As an example, this is what it looks like currently if you use a dropdown and a button

<img width="852" alt="Screen Shot 2021-05-05 at 10 32 28 AM" src="https://user-images.githubusercontent.com/35148959/117168601-eb9f1f00-ad8d-11eb-95ca-79a15b16d51d.png">

And here is what that looks like with this change3

<img width="871" alt="Screen Shot 2021-05-05 at 10 32 20 AM" src="https://user-images.githubusercontent.com/35148959/117168574-e510a780-ad8d-11eb-9cf5-9bfbdcaa4b6b.png">

2021-05-05 21:46 UTC, mcoker approved these changes

2021-05-06 17:34 UTC, merged

2021-05-06 22:11 UTC, patternfly-build commented
:tada: This PR is included in version 4.103.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.103.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.103.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: