feat(helper-text): added helper text component
patternfly/patternfly pull request #4089
Opened 2021-05-20 23:03 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/4017

Adds 2 types of helper texts:

### Static
This is the default helper text. With static helper text, the text color and icon color are the same. By default the text and optional icon are black. Indeterminate is grey, warning is yellow, success is green, invalid is red.

### Dynamic
This is an opt in to the helper text component. By default a dynamic helper text and icon are black. Intermediate is grey, warning has yellow icon and grey text, success has green icon and grey text, and invalid has red icon and black text.

A helper text component is a block made up of helper text items. There can be one or more items, and if there are multiple items in a helper text block, there is a `xs` spacer between items. A block of multiple items can be regular divs (in the case of regular helper text that isn't necessarily a list), or an HTML list (particularly useful in dynamic/validation helper text).

2021-05-20 23:07 UTC, patternfly-build commented
Preview: https://patternfly-pr-4089.surge.sh

2021-05-21 13:58 UTC, mcarrano reviewed
This looks good @mcoker . My only feedback is that I think the yellow/warning version should use the darker gold text color for better contrast/readability. @mceledonia @doruskova @ajacobs21e can you also take a look?

2021-05-21 14:02 UTC, doruskova reviewed
Agree with @mcarrano. The warning text should use `--pf-global--warning-color--200` because the light yellow is not accessible. However, it looks great! Thank you!

2021-05-24 16:07 UTC, mcoker commented
@mcarrano @doruskova thanks! Looking at the alert, we use `success/warning/danger-color--100` for the icon and `success/warning/danger-color--200` for the text. Should I use that here? 

In the form component, the error helper text and icon both are `danger-color--100`, however I'm not sure that's the correct implementation. We do not have a unique icon color for the form component helper text for any of the states. This is what it looks like currently - the success color is `success-color--200`, warning is `warning-color--200`.

<img width="861" alt="Screen Shot 2021-05-24 at 11 05 24 AM" src="https://user-images.githubusercontent.com/35148959/119375107-04f60580-bc80-11eb-9dc8-6549183ce281.png">


Here is this helper text PR with icon/text color that matches the alert component with `success/warning/danger-color--100` for the icon and `success/warning/danger-color--200` for the text.

<img width="300" alt="Screen Shot 2021-05-24 at 11 06 08 AM" src="https://user-images.githubusercontent.com/35148959/119375228-3078f000-bc80-11eb-8454-fb2d5ccd6992.png">

2021-05-24 17:35 UTC, mcoker commented
@mcarrano great, those color updates are in the PR now.

2021-05-24 18:57 UTC, mcoker commented
@mcarrano btw I called this component "Helper text" - is that OK or do you want to name it "Rich helper text"?

2021-05-24 21:13 UTC, mcarrano commented
I think that the name is fine @mcoker . It's more likely people will look for it under this name.

2021-05-24 21:14 UTC, mcarrano approved these changes
Looks good.

2021-05-25 08:19 UTC, doruskova commented
@mcoker Looks great!

2021-05-25 13:26 UTC, mattnolting requested changes
Hey @mcoker, this is looking great! Couple of questions

- Not sure I understand the static/dynamic concept. It looks like they could be used interchangeably, based on messaging and/or intent. 

In this example, I would assume both helper texts are dynamic, but I wouldn't inherently know which variant to use. 

![Screen Shot 2021-05-25 at 9 18 45 AM](https://user-images.githubusercontent.com/5385435/119505364-de48d500-bd3a-11eb-8c7c-a58cc76b1a16.png)

I think this could be solved by either changing `dynamic` to another name or adding documentation explaining when to use which variant. 

- Looks like you need to add standard documentation at the end of `HelperText.md`

2021-05-25 13:28 UTC, mattnolting commented on src/patternfly/components/HelperText/helper-text.scss
> +  }
🤩

2021-05-25 19:29 UTC, mcoker commented
@mattnolting updated the docs

2021-05-26 17:42 UTC, mcoker commented
@mattnolting I chatted with @mcarrano offline about the confusion using the dynamic modifier, and didn't have an obvious solution. I'm fine with merging it as is and following up if we need to. wdyt?

2021-05-26 17:56 UTC, mattnolting approved these changes
LAPTM 😄  Let's follow up w/naming the variant.

2021-05-26 18:34 UTC, merged

2021-05-26 18:58 UTC, patternfly-build commented
:tada: This PR is included in version 4.106.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.106.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.106.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: