fix(drawer): added panel min-width
patternfly/patternfly pull request #4091
Opened 2021-05-21 11:03 UTC by mattnolting

closes #3795

2021-05-21 11:07 UTC, patternfly-build commented
Preview: https://patternfly-pr-4091.surge.sh

2021-05-21 11:45 UTC, DaoDaoNoCode approved these changes
Look 😎 to me, thanks @mattnolting !

2021-05-24 21:50 UTC, mcoker requested changes
Looks great! Can you also add support for a `min-height` (and undo the `min-width`) on the `.pf-m-panel-bottom` variation? Looks like we have the same problem with the shadow there.

2021-05-26 00:10 UTC, mcoker approved these changes
LPTM! 🏆

2021-05-26 00:11 UTC, merged

2021-05-26 00:35 UTC, patternfly-build commented
:tada: This PR is included in version 4.104.4 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.104.4)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.104.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: