fix(tree-table): added actions support
patternfly/patternfly pull request #4135
Opened 2021-06-08 16:02 UTC by mattnolting

closes #4075

2021-06-08 16:06 UTC, patternfly-build commented
Preview: https://patternfly-pr-4135.surge.sh

2021-06-09 14:29 UTC, nicolethoen approved these changes
this is magical

2021-06-09 16:07 UTC, mcoker reviewed
Looks really great!!

Left a couple of questions about vars.

2021-06-09 18:58 UTC, mcarrano requested changes
I think this works @mattnolting , but I was a little uncomfortable with the two kabob icons (horz and vertical) grouped like that. I brainstormed with @mceledonia a bit and we came up with another idea. Can we take the "show more (...)" kabob and move it so that it's left aligned after the node label? The result would look something like this...

![Tree-table-actions](https://user-images.githubusercontent.com/6619860/121412812-17846600-c933-11eb-8683-af31f410c8cb.png)

We recommed using a 24px spacer between the text and the (...) icon button. What do you think? Note: I'd suggest this a consistent placement whether there are actions on the row or not.

2021-06-09 19:14 UTC, mattnolting commented on src/patternfly/components/Table/table-tree-view.scss
> +.pf-c-table__actions {
![Screen Shot 2021-06-09 at 3 14 19 PM](https://user-images.githubusercontent.com/5385435/121415172-6f23d100-c935-11eb-9018-92dd0a47b643.png)

2021-06-09 19:26 UTC, mcoker commented on src/patternfly/components/Table/table-tree-view.scss
> +.pf-c-table__actions {
the element in the css is `.pf-c-table__actions` (plural)

2021-06-09 19:33 UTC, mattnolting commented on src/patternfly/components/Table/table-tree-view.scss
> +.pf-c-table__actions {
Ah, missed it

2021-06-09 19:33 UTC, mattnolting commented on src/patternfly/components/Table/table-tree-view.scss
> +.pf-c-table__actions {
Updated

2021-06-09 20:19 UTC, nicolethoen approved these changes

2021-06-09 20:37 UTC, mcarrano approved these changes
I like this much better. Thanks for making that change @mattnolting .  

@mceledonia can you also take a look?

2021-06-09 21:17 UTC, mcoker commented on src/patternfly/components/Table/table-tree-view.scss
>        --pf-c-table--cell--PaddingTop: var(--pf-c-table--m-tree-view-grid--tbody--node--PaddingTop);
Should we update this var to match the one below? Also we could nest the rule below in this block.

2021-06-09 21:21 UTC, mcoker commented
Looks like the thead row border doesn't extend to the end in safari. 

<img width="1220" alt="Screen Shot 2021-06-09 at 4 20 24 PM" src="https://user-images.githubusercontent.com/35148959/121431131-9fbc3880-c93e-11eb-95ad-a78ab1dd47e3.png">

2021-06-10 18:31 UTC, mattnolting commented
@mcoker updated

2021-06-11 22:02 UTC, mcoker approved these changes
L🍕TM!!

2021-06-11 22:03 UTC, merged

2021-06-11 22:20 UTC, patternfly-build commented
:tada: This PR is included in version 4.110.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.110.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.110.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: