feat(search-input): added variant with submit button
patternfly/patternfly pull request #4180
Opened 2021-06-21 20:02 UTC by bitwiseor

fixes #4036 

Added a variant of the SearchInput component with a submit button, also added an example on the component page for SearchInput.

2021-06-21 20:07 UTC, patternfly-build commented
Preview: https://patternfly-pr-4180.surge.sh

2021-06-21 20:17 UTC, mcoker requested changes
Perfect!! Great job. One change that's a pre-existing issue is I noticed the search button is `type="button"`. Looks like we're using `type="submit"` in the react component, and that seems more appropriate. Would you mind updating the button in [search-input-search-button.hbs](https://github.com/patternfly/patternfly/blob/da311aa862ab8ea76ebb2018ba813b48515e685b/src/patternfly/components/SearchInput/search-input-search-button.hbs) to be `type="submit"`? Looks like we offer that via `button--IsSubmit` in [button.hbs](https://github.com/patternfly/patternfly/blob/e6045c0b7ae3280b25bd8596cf4da29d2e4b67f4/src/patternfly/components/Button/button.hbs#L2-L3)

2021-06-22 15:24 UTC, bitwiseor commented
Updated so the search input search button is of type "submit"!

2021-06-22 15:33 UTC, mcoker approved these changes
🥳👍

2021-06-23 19:41 UTC, merged

2021-06-23 20:15 UTC, patternfly-build commented
:tada: This PR is included in version 4.117.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.117.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.117.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: