fix(wizard): switched ol to span in wizard toggle
patternfly/patternfly pull request #4237
Opened 2021-07-26 17:45 UTC by bitwiseor

fixes #2202 

Needs double checking; I'm not sure where in my dev server to find the relevant demos to verify that this is correct 😨

2021-07-26 17:50 UTC, patternfly-build commented
Preview: https://patternfly-pr-4237.surge.sh

2021-07-26 18:49 UTC, mcoker requested changes
> I'm not sure where in my dev server to find the relevant demos to verify that this is correct

@bitwiseor you can look at any of the examples or demos on https://patternfly-pr-4237.surge.sh/components/wizard.

The change is in the top nav toggle. You'll want to verify the layout matches what's currently in main on patternfly.org both in the collapsed and expanded states. 

The layout looks good to me! Just one comment about the element of the lists direct children.

2021-07-26 18:49 UTC, mcoker commented on src/patternfly/components/Wizard/wizard-toggle-list.hbs
> +<span class="pf-c-wizard__toggle-list{{#if wizard-toggle-list--modifier}} {{wizard-toggle-list--modifier}}{{/if}}"
This looks good, but looks like the children of this element (`.pf-c-wizard__toggle-list-item`) are still `<li>`s, which is invalid in a `<span>`.

2021-07-27 20:33 UTC, mcoker requested changes
Looks good! Can you also update the docs to list the new elements?

<img width="868" alt="Screen Shot 2021-07-27 at 3 32 34 PM" src="https://user-images.githubusercontent.com/35148959/127223469-be6d2c72-30f6-4c08-ab42-74f6bb709d24.png">

2021-07-27 21:06 UTC, mcoker approved these changes
LGTM! @jessiehuff are there any a11y concerns with this change from an `ol` to `span`s?

2021-07-28 20:41 UTC, jessiehuff approved these changes
So I tested in VO, JAWS, and NVDA, and all of them sound the same as what's currently in org so it seems ok to me. I did notice that in NVDA the wizard step number and the wizard step button are being read as two separate buttons for some reason, but I don't think it's related to this PR since when I tested org I got the same result.

2021-07-28 20:43 UTC, merged

2021-07-28 21:03 UTC, patternfly-build commented
:tada: This PR is included in version 4.124.4 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.124.4)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.124.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: