fix(examples): updates before leave
patternfly/patternfly pull request #4285
Opened 2021-08-11 13:46 UTC by evwilkin

Closes #4023 

This PR updates microcopy across many Core examples & demos, per the notes in the original issue (further discussion in [this doc](https://docs.google.com/document/d/1Lqa8turRxmYNn05hDUPykM-q4vQDoWyuVfy3qasXlGU/edit)).

2021-08-11 13:52 UTC, patternfly-build commented
Preview: https://patternfly-pr-4285.surge.sh

2021-08-12 14:00 UTC, evwilkin commented
@abigaeljamie @afialkoff the microcopy updates for the Core examples & demos are ready for review, there were some discrepancies originally in the doc so LMK as any questions arise.

2021-08-12 17:35 UTC, mcoker approved these changes
LGTM!

2021-08-12 17:35 UTC, mcoker commented on src/patternfly/components/InputGroup/examples/InputGroup.md
> -<br>
🤠👍

2021-08-17 13:15 UTC, afialkoff requested changes
Hi @evwilkin, thanks again for tackling these example/demo microcopy edits! I suggested a few small changes: 

- Removing one period from "Required field" error-state helper text 
- Writing the "PatternFly logo" alt text in sentence case 

Other than those small fixes, these look good to go! 👍

2021-08-17 13:15 UTC, afialkoff commented on src/patternfly/demos/CardView/examples/CardView.md
> +        {{#> brand brand--attribute='src="/assets/images/PF-Masthead-Logo.svg" alt="PatternFly Logo"'}}{{/brand}}
```suggestion
        {{#> brand brand--attribute='src="/assets/images/PF-Masthead-Logo.svg" alt="PatternFly logo"'}}{{/brand}}
```

2021-08-17 13:15 UTC, afialkoff commented on src/patternfly/demos/Alert/examples/horizontal-form.hbs
> +          Required field.
Since we're replacing full-sentence error text ("This is a required field.") with a fragment, we can remove this period!

2021-08-17 18:25 UTC, evwilkin commented
@afialkoff I've made updates based on your recommendations, if you can take another look that would be great!

2021-08-17 20:17 UTC, afialkoff approved these changes
Everything looks good to me, @evwilkin! 🙂👍

2021-08-18 17:36 UTC, mcoker approved these changes

2021-08-18 19:26 UTC, merged

2021-08-18 19:51 UTC, patternfly-build commented
:tada: This PR is included in version 4.132.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.132.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.132.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: