fix(docs): add Extensions to workspace nav, move LogViewer to extensions
patternfly/patternfly pull request #4286
Opened 2021-08-11 13:58 UTC by evwilkin

Closes #4279 

This PR adds an "Extensions" section to the Core workspace and moves the Log viewer from "Components" to "Extensions"

2021-08-11 14:05 UTC, patternfly-build commented
Preview: https://patternfly-pr-4286.surge.sh

2021-08-11 15:59 UTC, mcoker requested changes
Change LGTM! Though there are some example specific styles in https://github.com/patternfly/patternfly/blob/702465bf71de85ea5387ee4b32624f89374fb591/src/patternfly/components/LogViewer/examples/LogViewer.css that look like they need to be updated. Probably a search/replace for `#ws-core-c` w/ `#ws-core-e`

2021-08-11 20:03 UTC, evwilkin commented
@mcoker updated - it looks like the `#ws-core-e-log-viewer-responsive` styles were unused, I've removed those as well but LMK if they should be added back in.

2021-08-11 20:19 UTC, mcoker approved these changes
LGTM!

2021-08-17 17:42 UTC, nicolethoen approved these changes

2021-08-17 17:42 UTC, merged

2021-08-17 17:54 UTC, patternfly-build commented
:tada: This PR is included in version 4.131.1 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.131.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.131.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: