feat(utilities): add text and background utilities
patternfly/patternfly pull request #4292
Opened 2021-08-12 13:25 UTC by srambach

This adds in additional text color and background color utilities.

Fixes #3642

2021-08-12 13:31 UTC, patternfly-build commented
Preview: https://patternfly-pr-4292.surge.sh

2021-08-12 16:25 UTC, mcoker requested changes
Looks great! Just a few small things I noticed.

2021-08-12 16:25 UTC, mcoker commented on src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
> +| `.pf-u-background-color-dark-400` | `*`        | Applies background color dark 200. |
```suggestion
| `.pf-u-background-color-dark-400` | `*`        | Applies background color dark 400. |
```

2021-08-12 16:25 UTC, mcoker commented on src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
> +| `.pf-u-background-color-200`      | `*`        | Applies background color 200.      |
Looks like we're missing docs for these


```
  background-color-active-color-100: (
    background-color var(--pf-global--active-color--100)
  ),
  background-color-active-color-300: (
    background-color var(--pf-global--active-color--300)
  ),
  background-color-primary-color-200: (
    background-color var(--pf-global--primary-color--100)
  ),
```

2021-08-12 16:25 UTC, mcoker commented on src/patternfly/utilities/Text/examples/Text.md
> -| `.pf-u-active-color-300`    | `*`        | Sets font-color to Active Color 300    |
Are we removing `active-color-200/300`? If so, looks like they are still in the CSS:

https://github.com/patternfly/patternfly/blob/e3962b3df7ada7a975af955dca7ac07146169eff/src/patternfly/utilities/Text/text.scss#L98-L103

2021-08-12 16:25 UTC, mcoker commented on src/patternfly/utilities/Text/text.scss
> +    color var(--pf-global--link--Color--dark-hover)
```suggestion
    color var(--pf-global--link--Color--dark--hover)
```

2021-08-12 16:25 UTC, mcoker commented on src/patternfly/utilities/Text/examples/Text.md
> -| `.pf-u-secondary-color-100` | `*`        | Sets font-color to Secondary Color 100 |
primary-200 and secondary-100 are still in the css

https://github.com/patternfly/patternfly/blob/e3962b3df7ada7a975af955dca7ac07146169eff/src/patternfly/utilities/Text/text.scss#L116-L121

2021-08-12 16:26 UTC, mcoker commented on src/patternfly/utilities/Text/examples/Text.md
>  | `.pf-u-color-200`           | `*`        | Sets font-color to Color 200           |
Also can you update these docs to be sentence case?

2021-08-12 21:55 UTC, mcoker approved these changes
fantastic! 🎉

2021-08-16 17:47 UTC, mceledonia approved these changes
Looks good to me!

2021-08-17 15:09 UTC, mcarrano reviewed
I will defer to @mceledonia and @mcoker on this one.

2021-08-17 15:10 UTC, merged

2021-08-17 15:38 UTC, patternfly-build commented
:tada: This PR is included in version 4.131.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.131.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.131.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: