fix(tabs): moved text into expandable toggle
patternfly/patternfly pull request #4333
Opened 2021-08-25 21:34 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/4174

I left legacy examples since we need to support both variations of the markup until a breaking change. I'll open a breaking change PR to remove the legacy support if this PR is merged.

2021-09-08 15:32 UTC, mattnolting requested changes
Looks good, need to control long strings

![Screen Shot 2021-09-08 at 11 30 18 AM](https://user-images.githubusercontent.com/5385435/132539597-87f5c52c-2034-4290-a5ef-4fb5619e87c3.png)

2021-09-08 18:53 UTC, mcoker commented
@mattnolting good catch, updated so the text wraps and the toggle button is aligned to the top to match the existing wrap behavior.

2021-09-09 14:33 UTC, mattnolting approved these changes
Great work, LPTM!

2021-09-09 14:34 UTC, merged

2021-09-09 14:53 UTC, patternfly-build commented
:tada: This PR is included in version 4.135.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.135.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.135.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: