feat(label): added compact variant
patternfly/patternfly pull request #4386
Opened 2021-09-21 01:27 UTC by mattnolting

closes #4160

2021-09-21 01:40 UTC, patternfly-build commented
Preview: https://patternfly-pr-4386.surge.sh

2021-09-21 19:01 UTC, mcoker requested changes
Looks good! I'm assuming you can have icons and an optional close button? If so, the current close button overflows the label. I suppose that's OK given the target area for the button would be tiny if it were contained inside the label. cc @mceledonia 

<img width="182" alt="Screen Shot 2021-09-21 at 1 59 30 PM" src="https://user-images.githubusercontent.com/35148959/134231672-d0dbf586-4420-480a-997a-e131c5ad5324.png">
<img width="248" alt="Screen Shot 2021-09-21 at 1 59 11 PM" src="https://user-images.githubusercontent.com/35148959/134231675-bf9abdeb-78bf-456b-9ee7-36f605ae8778.png">

2021-09-21 19:02 UTC, mceledonia commented
I think that's fine @mcoker I would rather have a larger click target than a smaller one for a11y purposes.

2021-09-21 21:10 UTC, mcarrano commented
There is currently an open design issue for this here: https://github.com/patternfly/patternfly-design/issues/1048. @gonoraj can you take a look at this and make sure it aligns with what you were thinking?

2021-09-23 17:13 UTC, mcoker requested changes

2021-09-23 17:13 UTC, mcoker commented on src/patternfly/components/Label/label.scss
> +  --pf-c-label--m-compact--FontSize: #{pf-font-prem(12px)};
@mattnolting ping - can you use the global var here?

2021-09-28 20:46 UTC, mcarrano approved these changes
Looks good to me! Thanks @mattnolting .

2021-09-28 20:47 UTC, mcoker approved these changes
🏆

2021-09-28 20:47 UTC, merged

2021-09-28 21:06 UTC, patternfly-build commented
:tada: This PR is included in version 4.138.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.138.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.138.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: