chore(utilities): add breakpoint options to docs
patternfly/patternfly pull request #4409
Opened 2021-10-01 13:13 UTC by srambach

Fixes #3702 

Adds documentation about breakpoints to the text and background color utilities and consolidates some repeated options.

2021-10-01 13:31 UTC, patternfly-build commented
Preview: https://patternfly-pr-4409.surge.sh

2021-10-01 17:54 UTC, mcoker requested changes

2021-10-01 17:54 UTC, mcoker commented on src/patternfly/utilities/Text/examples/Text.md
> +| `.pf-u-font-weight-{light, normal, bold}{-on-[breakpoint]}`            | `*`        | Sets font-size to light, normal, bold               |
nit - missing a conjunction
```suggestion
| `.pf-u-font-weight-{light, normal, bold}{-on-[breakpoint]}`            | `*`        | Sets font-size to light, normal, or bold               |
```

2021-10-01 17:54 UTC, mcoker commented on src/patternfly/utilities/Text/examples/Text.md
> +| `.pf-u-font-size-{xs, sm, md, lg, xl, 2xl, 3xl, 4xl}{-on-[breakpoint]}`| `*`        | Sets font-size to xs, sm, md, lg, xl, 2xl, 3xl, 4xl |
nit - missing a conjunction
```suggestion
| `.pf-u-font-size-{xs, sm, md, lg, xl, 2xl, 3xl, 4xl}{-on-[breakpoint]}`| `*`        | Sets font-size to xs, sm, md, lg, xl, 2xl, 3xl, or 4xl |
```

2021-10-05 13:35 UTC, mattnolting approved these changes
LPTM🚀

2021-10-05 14:04 UTC, mcoker approved these changes
🤩

2021-10-05 14:04 UTC, merged

2021-10-05 15:54 UTC, patternfly-build commented
:tada: This PR is included in version 4.142.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.142.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.142.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: