feat(menu-toggle): added plain w/text variant
patternfly/patternfly pull request #4491
Opened 2021-11-04 20:55 UTC by mattnolting

closes #4407

2021-11-04 22:21 UTC, mcoker requested changes
just a few example updates

2021-11-04 22:21 UTC, mcoker commented on src/patternfly/components/MenuToggle/examples/MenuToggle.md
> +{{#> menu-toggle menu-toggle--IsDisabled="true"}}
```suggestion
{{#> menu-toggle menu-toggle--IsDisabled="true" menu-toggle--IsPlain="true" menu-toggle--IsText="true"}}
```

2021-11-04 22:21 UTC, mcoker commented on src/patternfly/components/MenuToggle/examples/MenuToggle.md
> +{{#> menu-toggle menu-toggle--IsExpanded="true" menu-toggle--IsPlain="true" menu-toggle--IsText="true"}}
```suggestion
{{#> menu-toggle menu-toggle--IsPlain="true" menu-toggle--IsText="true"}}
```

2021-11-04 22:21 UTC, mcoker commented on src/patternfly/components/MenuToggle/examples/MenuToggle.md
> +{{#> menu-toggle menu-toggle--IsPlain="true" menu-toggle--IsText="true"}}
```suggestion
{{#> menu-toggle menu-toggle--IsExpanded="true" menu-toggle--IsPlain="true" menu-toggle--IsText="true"}}
```

2021-11-04 22:21 UTC, mcoker commented on src/patternfly/components/MenuToggle/menu-toggle.scss
> +  &.pf-m-plain:not(.pf-m-text) {
🔥

2021-11-05 14:22 UTC, mcoker approved these changes
🤩PTM!

2021-11-05 14:23 UTC, mcoker commented
@mattnolting can you add this modifier to the docs?

2021-11-05 14:32 UTC, mattnolting commented
> @mattnolting can you add this modifier to the docs?

Oh, shoot. Yep, I'll add it!

2021-11-05 19:30 UTC, merged

2021-11-05 19:50 UTC, patternfly-build commented
:tada: This PR is included in version 4.154.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.154.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.154.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: