fix(dropdown): applied primary stying to split
patternfly/patternfly pull request #4508
Opened 2021-11-10 15:44 UTC by mattnolting

closes #4130

2021-11-10 16:02 UTC, patternfly-build commented
Preview: https://patternfly-pr-4508.surge.sh

2021-11-10 23:02 UTC, mcoker requested changes
LGTM, although hovering over the arrow gives this styling
<img width="183" alt="Screen Shot 2021-11-10 at 4 52 32 PM" src="https://user-images.githubusercontent.com/35148959/141206704-c4d6931e-587d-4b09-b1a3-b5fe07b22198.png">

@mcarrano @mceledonia can you also review please?

2021-11-11 15:57 UTC, mcarrano reviewed
I guess this is what was requested. But it looks really odd now that I see it. What do you think @mceledonia ?

2021-11-11 21:08 UTC, mcoker commented
@mattnolting - met with @mcarrano and looks like we can just remove the example with the checkbox. The checkbox shouldn't be used with the primary variation.

2021-11-11 22:58 UTC, mcoker approved these changes

2021-11-11 22:58 UTC, merged

2021-11-11 23:18 UTC, patternfly-build commented
:tada: This PR is included in version 4.157.1 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.157.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.157.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: