fix(focus): fixed focus styles for interactable elems
patternfly/patternfly pull request #4601
Opened 2022-01-11 21:03 UTC by mattnolting

fixes #4534 

This PR changes the default behavior of dropdown, context-selector, menu toggle and select. If element `:focus` + `mouseout`, focus/active/hover styles are reverted to default state.

2022-01-11 21:19 UTC, patternfly-build commented
Preview: https://patternfly-pr-4601.surge.sh

2022-01-12 19:58 UTC, srambach commented on src/patternfly/sass-utilities/mixins.scss
> +  @debug #{$namespace};
Did you mean to leave this here?

2022-01-12 20:08 UTC, mattnolting commented on src/patternfly/sass-utilities/mixins.scss
> +  @debug #{$namespace};
Nope, good catch

2022-01-17 22:42 UTC, mcoker requested changes
I love this change, my only hesitation is the change in specificity with the `:focus` styles. My inclination is that it's probably fine, but we've had issues with changing selectors/specificity and some apps' overrides no longer applying because they're targeting the override via specific selectors and not CSS vars. And until we have better docs that have been communicated well around how to make customizations using CSS vars, we've communicated that we would avoid changing selectors like this.

I put together a codepen that shows this, and also uses the `:where()` selector to reduce the specificity - https://codepen.io/mcoker/pen/BawbebY. That may work though we may need to use a custom selector per component based on the original focus style specificity. Just an idea.

These focus styles seem safe to update and I wouldn't expect much of a conflict with existing overrides, though these are some pretty common components, and I don't believe this as a high priority issue in this instance. Given that, I'm curious y'alls thoughts.

2022-01-19 15:24 UTC, mattnolting commented
@mcoker updated

2022-01-19 19:21 UTC, srambach commented
What is a value of having both `--base` and `--reset`? It looks like `--reset` is always the value of `--base` unless there wasn't a `--base` to start with?

2022-01-19 19:57 UTC, mattnolting commented
> What is a value of having both `--base` and `--reset`? It looks like `--reset` is always the value of `--base` unless there wasn't a `--base` to start with?

@srambach `--reset` allows for the variable to be accessed contextually, with a less specific selector, like

```
.pf-c-masthead .pf-c-dropdown {
  --pf-c-dropdown__toggle--before--BorderBottomColor--reset: {new-color};
}
```

2022-01-19 20:13 UTC, srambach approved these changes
LGTM

2022-01-21 01:14 UTC, mattnolting commented
After discussing w/@mcoker, `:focus-visible` at scale in favor of `:focus` will create the desired effect on intractable elements.

2022-01-21 01:14 UTC, closed without merging