Fix hover state for all plain variant icons
patternfly/patternfly pull request #4627
Opened 2022-01-19 18:21 UTC by srambach

Fixes #4552 

This changed the toggle icon to be darker on hover for dropdown, options menu, select, menu toggle, context selector, and pagination.

2022-01-19 18:36 UTC, patternfly-build commented
Preview: https://patternfly-pr-4627.surge.sh

2022-01-19 21:17 UTC, mcoker requested changes
Fantastic! Just one var name that needs to be updated.

2022-01-19 21:17 UTC, mcoker commented on src/patternfly/components/MenuToggle/menu-toggle.scss
> +  --pf-c-menu-toggle--m-plain--expanded__toggle-icon--Color: var(--pf-global--Color--100);
```suggestion
  --pf-c-menu-toggle--m-plain--expanded__toggle-icon--Color: var(--pf-global--Color--100);
```
```suggestion
  --pf-c-menu-toggle--m-plain--m-expanded__toggle-icon--Color: var(--pf-global--Color--100);
```

2022-01-19 21:17 UTC, mcoker commented on src/patternfly/components/MenuToggle/menu-toggle.scss
> +    --pf-c-menu-toggle--m-plain__toggle-icon--Color: var(--pf-c-menu-toggle--m-plain--expanded__toggle-icon--Color);
```suggestion
    --pf-c-menu-toggle--m-plain__toggle-icon--Color: var(--pf-c-menu-toggle--m-plain--m-expanded__toggle-icon--Color);
```

2022-01-19 22:08 UTC, mcoker approved these changes

2022-01-19 22:08 UTC, mattnolting commented
Looks like the primary/secondary dropdown caret changed

![Screen Shot 2022-01-19 at 5 07 38 PM](https://user-images.githubusercontent.com/5385435/150222022-fb71656e-aba5-476f-b3ee-5761e04009e7.png)

2022-01-19 22:11 UTC, mattnolting commented
Plain menu toggle doesn't have a color change

![Screen Shot 2022-01-19 at 5 10 11 PM](https://user-images.githubusercontent.com/5385435/150222320-f6afebc1-20c2-409c-9e26-cd3be496315a.png)

2022-01-19 22:14 UTC, mattnolting commented
Options menu hover doesn't seem to have a change

![Screen Shot 2022-01-19 at 5 14 14 PM](https://user-images.githubusercontent.com/5385435/150222764-4c856e5f-cd81-4b8a-93db-dcc57b0fc82c.png)

2022-01-19 22:53 UTC, srambach commented
> Plain menu toggle doesn't have a color change
> 
This is pre-existing and I don't think should be part of this PR. 

I think the primary/secondary dropdown color is fixed now.
I am seeing a color change on the options menu hover, are you sure you don't? @mattnolting 

Thanks for the inherit fallback idea @mcoker that works nicely.

2022-01-19 23:22 UTC, mcoker approved these changes
🥳

opened an issue about the plain menu toggle state colors here - https://github.com/patternfly/patternfly/issues/4630

2022-01-20 01:40 UTC, mattnolting approved these changes
LGTM!

2022-01-20 01:43 UTC, merged

2022-01-24 16:41 UTC, patternfly-build commented
:tada: This PR is included in version 4.171.1 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.171.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.171.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: