feat(pagination): remove number input arrow visibility
patternfly/patternfly pull request #4641
Opened 2022-01-25 22:13 UTC by jeffpuzzo

Closes: #4224

2022-01-25 22:28 UTC, patternfly-build commented
Preview: https://patternfly-pr-4641.surge.sh

2022-01-25 22:57 UTC, mcoker requested changes
This looks really good! Left a couple of comments.

Also one more update needed - we calculate the width of that input with 2 variables:
* `--pf-c-pagination__nav-page-select--c-form-control--width-chars` - the number of characters the input should show.
* `--pf-c-pagination__nav-page-select--c-form-control--width-base` - the base width of the input including the estimated width of the arrows that were removed in this PR.

Now that the arrows are gone, we should update the calculation that creates space for them in the width of that input. Here's the block where those vars are defined: 

https://github.com/patternfly/patternfly/blob/d57498cdc0946095da6f605e95067df610f52787/src/patternfly/components/Pagination/pagination.scss#L40-L42

FWIW we also do this in the number input, which may be good as a reference:

https://github.com/patternfly/patternfly/blob/d57498cdc0946095da6f605e95067df610f52787/src/patternfly/components/NumberInput/number-input.scss#L8-L11

2022-01-25 22:57 UTC, mcoker commented on src/patternfly/components/Pagination/pagination.scss
> +  input[type="number"] {
Can you test adding these styles under the `.pf-c-form-control` selector below? That selector should target this element without the need to define `input[...]`

2022-01-25 22:57 UTC, mcoker commented on src/patternfly/components/Pagination/pagination.scss
> +      appearance: none;
This is great! We do this in number input using an older technique. Any interest in updating that as part of this PR, too? If not we can make that a separate issue:

https://github.com/patternfly/patternfly/blob/d57498cdc0946095da6f605e95067df610f52787/src/patternfly/components/NumberInput/number-input.scss#L21-L29

2022-01-26 20:05 UTC, mcoker reviewed
This looks great, appreciate the DRY approach, and it matches the number input. Though I am noticing that there isn't always space for the number of characters to show via the `--width-chars` in both components. For example, "20" doesn't show correctly:

<img width="252" alt="Screen Shot 2022-01-26 at 1 54 28 PM" src="https://user-images.githubusercontent.com/35148959/151236953-be6bcb27-034a-4c4f-a9ec-d2e5ddb91e1f.png">

<img width="219" alt="Screen Shot 2022-01-26 at 1 54 32 PM" src="https://user-images.githubusercontent.com/35148959/151236949-acf51a0a-5b0c-4174-80ca-bd02dac24842.png">

<img width="283" alt="Screen Shot 2022-01-26 at 1 54 23 PM" src="https://user-images.githubusercontent.com/35148959/151236951-526388ed-e375-4417-9bd8-6a29c6aca238.png">

<img width="285" alt="Screen Shot 2022-01-26 at 1 54 19 PM" src="https://user-images.githubusercontent.com/35148959/151236954-0ee2d5b9-9dac-47ec-a0f8-e04f539351fb.png">

Seems like we should look into that a bit and make a small adjustment - do you agree @mcarrano @mmenestr?

Also this is going to change the visual width of the input, and if a user was either depending on the arrows and/or customized the input width, this could cause a visual issue for them. Just want to verify that's OK @mcarrano @mmenestr

2022-01-26 22:14 UTC, mcarrano commented
@mcoker Interestingly, I don't see the problem in Firefox, but I do in Chrome. I definitely think we need to address this, although I'm wary of adding more width since we could have cases where a pagination control is used in a toolbar with tight spacing. But is it true that overall we are reducing the with of the input by this PR? In that case maybe add some width back?

2022-01-26 22:15 UTC, jeffpuzzo commented
>

I will say that I didn't recognize this in the react example equivalent for pagination because it seems we're automatically setting the number count to what the max is, so entering 20 out of 4 wasn't an option there, so it was definitely overlooked.

Thanks to the help of @mcoker who pointed out the input border was causing this issue, and for providing the calculation itself, I think these should be all set now:
![image](https://user-images.githubusercontent.com/96431149/151255698-15d39438-6291-4d76-aa76-3f11c6638e1b.png)
![image](https://user-images.githubusercontent.com/96431149/151255750-dd9e21db-1ebc-4f5d-ba1b-11476684c78b.png)

2022-01-27 16:51 UTC, mcoker approved these changes
Awesome work @jeffpuzzo!! So much better!

2022-01-27 19:41 UTC, mcarrano approved these changes
Looks great @jeffpuzzo !

2022-01-31 23:58 UTC, merged

2022-02-01 00:22 UTC, patternfly-build commented
:tada: This PR is included in version 4.172.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.172.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.172.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: