fix(form): improve accessible label on form elements
patternfly/patternfly pull request #4714
Opened 2022-03-01 19:37 UTC by srambach

Fixes #4453 

This adds `aria-described` by on the form field "more info" buttons  and improves the `aria-label` text so that core matches patternfly-react.

2022-03-01 19:54 UTC, patternfly-build commented
Preview: https://patternfly-pr-4714.surge.sh

2022-03-01 21:40 UTC, mcoker requested changes
Looks great, but it looks like there are a bunch of other places we use this help button that may need updating.

I wonder if instead of a manual update, we could use the `form-group--id` field better. We would need to take the `-` out of it and either insert the hyphen manually when it's used to create an `id`, `for`, or whatever - ie, change code like `id="' form--id form-group--id '"` to `id="' form--id '-' form-group--id '"`. We could also just leave the hyphen out - pretty sure it's just to generate `id` and `for`, and as long as it's unique, doesn't matter to me what it is. Tho it's more readable with the hyphens. That may be even more complicated though.

2022-03-01 21:40 UTC, mcoker commented on src/patternfly/components/Form/examples/Form.md
> +      {{> form-group-label-help form-group-label-help--aria-label="More information for name field" form-group-label-help--aria-describedby=(concat form--id form-group--id)}}
this is unrelated, but I noticed this example and the regular horizontal example both use `form--id="form-horizontal"` - wold you mind updating this one to be unique?

2022-03-01 21:40 UTC, mcoker commented on src/patternfly/components/Form/examples/Form.md
> +      {{> form-group-label-help form-group-label-help--aria-label="More information for Label 1 field" form-group-label-help--aria-describedby=(concat form--id form-group--id)}}
nit - looks like you're mixing the case of some labels. they should probably all just be sentence case

```suggestion
      {{> form-group-label-help form-group-label-help--aria-label="More information for label 1 field" form-group-label-help--aria-describedby=(concat form--id form-group--id)}}
```

2022-03-02 16:21 UTC, mattnolting commented on src/patternfly/components/Form/examples/Form.md
> +      {{> form-group-label-help form-group-label-help--aria-label="More information for name field" form-group-label-help--aria-describedby=(concat form--id form-group--id)}}
Looks like https://github.com/patternfly/patternfly/pull/4714/files#diff-604e9154a4176f06e862bcb8493641aea5f98be03d3ea0e9935ca8935b229fdaR11 needs to be something like `{{#> form-group form-group--id=(concat form--id "-name")}}` or added to `form-group.hbs`

2022-03-22 14:51 UTC, srambach commented
@mcoker I added the capability to use the `form-group--id` in the .hbs. However when I started converting all the examples, I noticed that there are quite a few where the id would not result in an understandable name when read. (e.g. clientid and some that are further hyphenated because of nesting) Instead of creating inconsistency in the examples, I left all using the original method of passing in the entire help text string. Without having a specified string, it will fall back to use "More information for `form-group--id`" and then just the text "More information."

2022-03-23 21:14 UTC, mattnolting approved these changes
LPTM! 🎉

2022-03-23 21:39 UTC, mcoker approved these changes
Perfect!

2022-03-23 21:40 UTC, merged

2022-03-24 17:46 UTC, patternfly-build commented
:tada: This PR is included in version 4.184.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.184.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.184.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: