fix(build): updated build to include themes directory
patternfly/patternfly pull request #4728
Opened 2022-03-09 14:19 UTC by evwilkin

Closes #4700 

This PR makes the build process aware of the new `themes` directory so it is included in the `dist` directory to be shipped as part of the package.

2022-03-11 15:57 UTC, nicolethoen approved these changes

2022-03-15 19:14 UTC, nicolethoen requested changes
I'm noticing when I try to build that all the new dark theme related .css files are empty...

2022-03-15 19:18 UTC, mattnolting commented
Confirmed, I too am seeing empty `.css` files

2022-03-24 03:35 UTC, evwilkin commented
@nicolethoen @mattnolting thanks for the callout - I've updated to remove the empty CSS files from being generated.

FYI - I confirmed these files were producing empty CSS files correctly, as the source SASS files only contain mixins & SASS variable declarations but no actual style rules to compile down into CSS.  Each of these SASS files all roll up into the `src/patternfly/patternfly-theme-dark.scss` file which is compiled into `patternfly-theme-dark.css`, and all these theme `.scss` files are still shipped in the package.

2022-03-24 13:07 UTC, nicolethoen approved these changes

2022-03-24 16:07 UTC, mcoker approved these changes
LGTM!

2022-03-24 16:36 UTC, mattnolting approved these changes
LPTM 👍

2022-03-24 17:02 UTC, merged

2022-03-24 17:46 UTC, patternfly-build commented
:tada: This PR is included in version 4.184.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.184.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.184.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: