refactor(demos): added new page template to demos
patternfly/patternfly pull request #4741
Opened 2022-03-21 19:40 UTC by mattnolting

closes #4684

2022-03-21 19:56 UTC, patternfly-build commented
Preview: https://patternfly-pr-4741.surge.sh

2022-03-25 03:25 UTC, evwilkin commented on src/patternfly/demos/JumpLinks/examples/JumpLinks.md
> +      {{> jump-links-header}}
It looks like this is missing `jump-links-main` which makes these a center-aligned flex column, without this the demo is showing the jump links header inline with the jump links list on both desktop & mobile

2022-03-25 14:10 UTC, evwilkin requested changes
I did a visual review of all changed examples/demos and the only significant discrepancy is the horizontal jumplinks demo I noted not stacking correctly

2022-03-25 23:22 UTC, mcoker approved these changes
LGTM!!!

2022-03-26 00:45 UTC, merged

2022-03-28 16:22 UTC, patternfly-build commented
:tada: This PR is included in version 4.185.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.185.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.185.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: