feat(wizard): added drawer
patternfly/patternfly pull request #4778
Opened 2022-04-07 16:48 UTC by mattnolting

closes #4611

2022-04-07 17:07 UTC, patternfly-build commented
Preview: https://patternfly-pr-4778.surge.sh

2022-04-12 15:36 UTC, mattnolting commented
@katierik

2022-04-13 14:37 UTC, mattnolting commented on src/patternfly/components/Drawer/drawer.scss
> -  min-height: 0;
`min-height: 0` was causing the `:last-child` `.pf-c-drawer__body` to collapse. 

Before:
![Screen Shot 2022-04-13 at 10 31 29 AM](https://user-images.githubusercontent.com/5385435/163204760-94ab08aa-cddc-49f9-ae37-828ef1bae39b.png)

After:
![Screen Shot 2022-04-13 at 10 31 22 AM](https://user-images.githubusercontent.com/5385435/163204729-536c8d17-efad-4f76-bbc4-231f459395bc.png)

2022-04-18 14:27 UTC, mcoker requested changes

2022-04-18 14:27 UTC, mcoker commented on src/patternfly/components/Drawer/drawer.scss
> -  min-height: 0;
@mattnolting do you mind adding this declaration back in for the time being so we can test it a little more, and merge this PR? Opened a follow up issue here to follow up - https://github.com/patternfly/patternfly/issues/4797

2022-04-18 15:26 UTC, mcoker approved these changes
Great work!!! 🫵😎👍

2022-04-18 15:26 UTC, merged

2022-04-18 15:47 UTC, patternfly-build commented
:tada: This PR is included in version 4.191.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.191.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.191.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: