feat(table): added image and text example
patternfly/patternfly pull request #4853
Opened 2022-05-13 19:48 UTC by mattnolting

Closes #4606 

Preview:

2022-05-13 20:04 UTC, patternfly-build commented
Preview: https://patternfly-pr-4853.surge.sh

2022-05-17 23:03 UTC, mcoker requested changes
Looks good - left a couple of comments. And I think this needs to be moved to demos?

2022-05-17 23:03 UTC, mcoker commented on src/patternfly/components/Table/images/table--icon-github.hbs
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="currentColor" width="30px">
we don't want to ship these files with the npm package - can you move them to `/static/assets/images/`? (I think that's the dir that serves static images). fwiw, we already have the github and google logos in there. Not sure if they're the same ones, but you may be able to reuse them. We have gitlab, dropdox, and facebook, too.

2022-05-24 19:33 UTC, srambach reviewed
Left a comment about the wording of the demo explanation.
Besides, that, I did expect that when narrow, the text would wrap beside the logo as it is in the example in the issue, so that you could see what is happening with the alignment and so the text is still aligned between rows. Instead, the text wraps below the logo. Maybe these are two different cases, but I suspect the more common use would want the text to remain aligned. 
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/19825616/170117059-14dcbe2d-bb27-49ea-a2ee-c75b44b3e336.png">

2022-05-25 14:35 UTC, mattnolting commented
@srambach @mcoker updated!

2022-05-25 15:43 UTC, mcoker requested changes

2022-05-25 15:43 UTC, mcoker commented on src/patternfly/demos/Table/examples/Table.md
> +    {{#> table table--id="image-alignment-demo-table" table--grid="true" table--modifier="pf-m-grid-lg" table--attribute='aria-label="This is an example of how to control images in table cells."'}}
```suggestion
    {{#> table table--id="image-alignment-demo-table" table--grid="true" table--modifier="pf-m-grid-lg" table--attribute='aria-label="This is an example of how to control image and text alignment in table cells."'}}
```

2022-05-25 15:43 UTC, mcoker commented on src/patternfly/demos/Table/examples/Table.md
> +                  {{> table--icon-red-hat class="test"}}
```suggestion
                  {{> table--icon-red-hat}}
```

2022-05-25 15:43 UTC, mcoker commented on src/patternfly/assets/images/table--icon-github.hbs
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="currentColor" width="30px">
just a nit - these shouldn't need `table--` in the filename since we can use them globally.

2022-05-25 15:43 UTC, mcoker commented on src/patternfly/demos/Table/examples/Table.md
> +import './Table.css'
Does this file exist? I don't see it - https://github.com/patternfly/patternfly/tree/37f003a829d05765706337e0b95075ac5bf4d15c/src/patternfly/demos/Table/examples

2022-05-26 00:38 UTC, mcoker approved these changes
Woo!

2022-05-26 00:39 UTC, merged

2022-05-26 00:57 UTC, patternfly-build commented
:tada: This PR is included in version 4.196.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.196.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.196.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: