feat(dropdown): added secondary split toggle
patternfly/patternfly pull request #4897
Opened 2022-06-09 18:39 UTC by mattnolting

Closes #4798

2022-06-09 18:55 UTC, patternfly-build commented
Preview: https://patternfly-pr-4897.surge.sh

2022-06-09 19:43 UTC, mcarrano approved these changes
Looks great. Thanks @mattnolting !

2022-06-15 16:44 UTC, mcoker reviewed
Looks great! Just a few small things.

2022-06-15 16:44 UTC, mcoker commented on src/patternfly/components/Dropdown/dropdown.scss
>      --pf-c-dropdown__toggle--m-split-button--m-primary--child--BackgroundColor: var(--pf-c-dropdown__toggle--m-split-button--m-primary--child--m-expanded--BackgroundColor);
Can you leave a comment here to update this var name to `--pf-c-dropdown--m-expanded__toggle--m-split-button--m-primary--child--BackgroundColor` like you've done with the secondary var?

2022-06-15 16:44 UTC, mcoker commented on src/patternfly/components/Dropdown/dropdown.scss
> +    --pf-c-dropdown__toggle--m-secondary--m-split-button--child--before--BorderWidth: var(--pf-c-dropdown--m-expanded__toggle--m-secondary--m-split-button--button--before--BorderWidth);
should this be `--child`?

```suggestion
    --pf-c-dropdown__toggle--m-secondary--m-split-button--child--before--BorderWidth: var(--pf-c-dropdown--m-expanded__toggle--m-secondary--m-split-button--child--before--BorderWidth);
```

2022-06-15 16:44 UTC, mcoker commented on src/patternfly/components/Dropdown/dropdown.scss
> +      &:active {
I wonder if we should have unique vars for these states - seems like we do with the other variations.

2022-06-15 19:17 UTC, mattnolting commented
@mcoker updated!

2022-06-15 20:54 UTC, mcoker requested changes

2022-06-15 20:54 UTC, mcoker commented on src/patternfly/components/Dropdown/dropdown.scss
> +      --pf-c-dropdown__toggle--m-secondary--hover--before--BorderWidth: var(--pf-c-dropdown__toggle--m-secondary--m-split-button--focus--before--BorderWidth);
```suggestion
      --pf-c-dropdown__toggle--m-secondary--focus--before--BorderWidth: var(--pf-c-dropdown__toggle--m-secondary--m-split-button--focus--before--BorderWidth);
```

2022-06-15 20:54 UTC, mcoker commented on src/patternfly/components/Dropdown/dropdown.scss
> +      --pf-c-dropdown__toggle--m-secondary--hover--before--BorderWidth: var(--pf-c-dropdown__toggle--m-secondary--m-split-button--active--before--BorderWidth);
```suggestion
      --pf-c-dropdown__toggle--m-secondary--active--before--BorderWidth: var(--pf-c-dropdown__toggle--m-secondary--m-split-button--active--before--BorderWidth);
```

2022-06-15 22:34 UTC, mcoker approved these changes
👍👍

2022-06-15 22:34 UTC, merged

2022-06-15 22:53 UTC, patternfly-build commented
:tada: This PR is included in version 4.197.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.197.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.197.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: