Adds height breakpoints for sticky top and bottom modifiers
patternfly/patternfly pull request #4905
Opened 2022-06-14 20:52 UTC by srambach

This adds a set of vertical breakpoints that are used for sticky top and bottom modifiers on page components.
Fixes #3660 

As part of this, the functions and mixins for creating utilities were updated to allow creation of vertical breakpoint utilities.

There was previous discussion about whether to try to create two-dimensional media queries. After some thought working through it with this [codepen](https://codepen.io/srambach/pen/dydKQaV?editors=0100), I feel that it's a lot of overhead for not that much advantage. There are some cases that can't really be handled with separate height and width media queries, but I honestly think that would be a sign of a too-complicated design. [This article](https://www.kooslooijesteijn.net/blog/multidimensional-responsive-design-5-tips) helped me to believe that as well.

2022-06-14 21:08 UTC, patternfly-build commented
Preview: https://patternfly-pr-4905.surge.sh

2022-06-17 19:10 UTC, mcoker requested changes

2022-06-17 19:10 UTC, mcoker commented on src/patternfly/sass-utilities/mixins.scss
> +@mixin pf-utility-builder($props, $breakpoints: null, $direction:"width") {
```suggestion
@mixin pf-utility-builder($props, $breakpoints: null, $direction: "width") {
```

2022-06-17 20:19 UTC, mattnolting approved these changes
LGTM!!

2022-06-17 20:23 UTC, mcoker requested changes

2022-06-17 20:23 UTC, mcoker commented on src/patternfly/demos/Page/examples/Page.md
> +```hbs isFullscreen
```suggestion
```hbs isFullscreen isBeta
```

2022-06-17 20:39 UTC, mcoker approved these changes

2022-06-17 20:39 UTC, merged

2022-06-17 20:57 UTC, patternfly-build commented
:tada: This PR is included in version 4.199.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.199.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.199.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: