feat(number-input): added support for status icon
patternfly/patternfly pull request #4983
Opened 2022-07-18 19:42 UTC by srambach

This increases the overall width of the number input so that if a status icon is put onto the form control, the number will not be cut off, and the width will not change, causing the right side control to jump. 
Since this increases the size, it uses a modifier `.pf-m-has-icon` to indicate that a status icon may be contained within and the extra space should be added. This modifier can be removed in a breaking change.
https://patternfly-pr-4983.surge.sh/components/number-input

Fixes #4833

2022-07-18 19:49 UTC, patternfly-build commented
Preview: https://patternfly-pr-4983.surge.sh

2022-07-18 23:23 UTC, mcoker requested changes
Other than the base `--width-icon` needing a unit and a small comment about the class name, LGTM!

2022-07-18 23:23 UTC, mcoker commented on src/patternfly/components/NumberInput/number-input.scss
> +  &.pf-m-has-icon {
I would probably either call this icon or status. I looked and we don't have any other classes with `pf-m-[has/is]`.

2022-07-19 21:04 UTC, mcarrano approved these changes
This looks good to me. Thanks @srambach !

2022-07-19 23:22 UTC, mcoker requested changes
looks awesome!! Just a couple of nits with the `--id` param, which is creating `name` attributes on the text inputs with the same values between examples.

2022-07-19 23:22 UTC, mcoker commented on src/patternfly/components/NumberInput/examples/NumberInput.md
> +{{#> number-input number-input--id="number-input-default" number-input--modifier="pf-m-status"}}
```suggestion
{{#> number-input number-input--id="number-input-status" number-input--modifier="pf-m-status"}}
```

2022-07-19 23:22 UTC, mcoker commented on src/patternfly/components/NumberInput/examples/NumberInput.md
> +{{#> number-input number-input--id="number-input-default" number-input--modifier="pf-m-status"}}
```suggestion
{{#> number-input number-input--id="number-input-status-warning" number-input--modifier="pf-m-status"}}
```

2022-07-20 14:41 UTC, mcoker approved these changes
🥳

2022-07-20 14:45 UTC, merged

2022-07-20 15:16 UTC, patternfly-build commented
:tada: This PR is included in version 4.204.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.204.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.204.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: