feat(page): adds full-height modifier
patternfly/patternfly pull request #5018
Opened 2022-08-02 19:08 UTC by srambach

This adds a modifier to the page component that sets the height using viewport units to eliminate the need to ensure that all elements above the page are set to 100% height.

Fixes #4822

2022-08-02 19:15 UTC, patternfly-build commented
Preview: https://patternfly-pr-5018.surge.sh

2022-08-02 21:42 UTC, mcoker requested changes
🤗 so cool! Still testing but saw this one bit in the docs.

2022-08-02 21:42 UTC, mcoker commented on src/patternfly/demos/Page/examples/Page.md
> +Using the `pf-m-full-height` modifier on the page component eliminates the need to ensure that the `<html>` and `<body>` tags, and any other tags above `.pf-c-page`, have height set to 100%.
```suggestion
Using the `.pf-m-full-height` modifier on the page component eliminates the need to ensure that the `<html>` and `<body>` tags, and any other ancestors of `.pf-c-page`, have height set to 100%.
```

2022-08-02 21:44 UTC, mcoker commented on src/patternfly/demos/Page/examples/Page.md
> +Using the `pf-m-full-height` modifier on the page component eliminates the need to ensure that the `<html>` and `<body>` tags, and any other tags above `.pf-c-page`, have height set to 100%.
Oh sorry I meant to give more context here. Wanted to say maybe use `.` with the class and/or say "modifier _class_" just so it's clear it's a class. Also that we use "ancestors" on the react side when referring to the elements above page, that seems a little clear. https://www.patternfly.org/v4/components/page/react-demos

> To make the page take up the full height, it is recommended to set the height of all ancestor elements up to the page component to 100%

2022-08-04 00:05 UTC, mcoker requested changes
Woooo! This is great. I was testing on mobile safari and saw the notorious `100vh` bug, but dug in a little and looks like it's because that's used in the website/workspace CSS 🤦‍♂️ - https://github.com/patternfly/patternfly-org/blob/532c94559691a461aaa248851e150744b15f01ab/packages/documentation-framework/global.css#L2-L6

```
#root,
#ws-router,
#ws-page {
  height: 100vh;
}
```

I'd love to merge this, then update the workspaces/website to test it out. I'm thinking we would
* replace `height: 100vh` with `100%` on those elements just for consistency with what we recommend to users
* add `.pf-m-full-height` to the page component that serves the docs.

One thing this would break is with our current demo for how to put a banner above and below the page component, but I'm wondering if we could do something better there instead. For reference, here's the [core banner demo](https://www.patternfly.org/v4/components/banner/html-demos/topbottom/) and the [react banner demo](https://www.patternfly.org/v4/components/banner/react-demos/top-and-bottom-banner/)

2022-08-04 16:06 UTC, mcoker approved these changes
🚀

2022-08-09 19:33 UTC, mattnolting reviewed
I think this is looking great. I would suggest adding a `.pf-c-page__top-container` and `.pf-c-page__bottom-container` for miscellaneous items (banners) that appear outside of standard page elements. Then we could move banners into those elements for corresponding demos. 

@mcoker wdyt?

2022-08-17 14:33 UTC, mattnolting approved these changes
LGTM! 🎉

2022-08-17 14:39 UTC, merged

2022-08-17 14:57 UTC, mturley commented
Awesome!

2022-08-17 15:07 UTC, patternfly-build commented
:tada: This PR is included in version 4.208.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.208.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.208.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: