fix(wizard): adjust dark theme colors
patternfly/patternfly pull request #5020
Opened 2022-08-03 20:37 UTC by srambach

Fixes #4978

2022-08-03 20:44 UTC, patternfly-build commented
Preview: https://patternfly-pr-5020.surge.sh

2022-08-03 23:07 UTC, mcoker requested changes
Just one small thing

2022-08-04 14:53 UTC, mcoker approved these changes
🥳

2022-08-04 20:53 UTC, mmenestr approved these changes

2022-08-04 21:22 UTC, mcarrano approved these changes
Looks good to me!

2022-08-16 19:18 UTC, merged

2022-08-16 19:48 UTC, patternfly-build commented
:tada: This PR is included in version 4.207.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.207.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.207.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: