chore(beta-components): promote 2022.14 candidates
patternfly/patternfly pull request #5179
Opened 2022-10-17 18:30 UTC by nicolethoen

Closes #5178

2022-10-17 18:36 UTC, patternfly-build commented
Preview: https://patternfly-pr-5179.surge.sh

2022-10-17 20:43 UTC, mcarrano requested changes
Looks good @nicolethoen except for Code Editor. Looks like you missed that one.

2022-10-18 19:34 UTC, nicolethoen commented
good catch!

2022-10-19 00:51 UTC, mcarrano approved these changes
Looks good. Thanks @nicolethoen !

2022-10-25 21:07 UTC, mcoker approved these changes
Nice!

2022-10-25 21:07 UTC, mcoker commented on src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md
> -beta: true
🥳

2022-10-25 21:07 UTC, merged

2022-10-27 14:10 UTC, patternfly-build commented
:tada: This PR is included in version 4.219.2 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v4.219.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/4.219.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: