refactor(background-image): updated bg image
patternfly/patternfly pull request #5328
Opened 2023-01-12 19:03 UTC by mattnolting

closes #5282

2023-01-12 19:07 UTC, patternfly-build commented
Preview: https://patternfly-pr-5328.surge.sh

2023-01-24 00:06 UTC, mcoker reviewed
A few comments. I also wonder if we should build in some image replacement at different viewport sizes? Kinda like the brand component supports.

2023-02-02 18:53 UTC, mcarrano reviewed
This looks great. My only critique is that the login page looks a bit odd in dark mode since there is not much is any differentiation between the login form and the background.

<img width="948" alt="Screenshot 2023-02-02 at 1 50 29 PM" src="https://user-images.githubusercontent.com/6619860/216422013-7b469889-71ae-4089-9b2d-52614a2d8eb3.png">

Not sure what to do about that, but feels like the space occupied by the login form shoukd be better defined. Thoughts @mceledonia ?

2023-02-23 00:31 UTC, mcarrano approved these changes
This looks great @mattnolting . Thanks for making those changes.

2023-03-07 16:52 UTC, thatblindgeye requested changes

2023-03-07 16:52 UTC, thatblindgeye commented on src/patternfly/components/BackgroundImage/background-image.scss
> +  content: "";
This could be removed.

2023-03-15 17:58 UTC, srambach reviewed
AFAICT, there is no documentation about how a product would replace the PatternFly logo with their own since it's no longer a separate element and is a background image instead. I assume the React implementation would provide a prop for it, but it really should also be documented in core since this is a common customization that will happen.

2023-03-16 18:19 UTC, thatblindgeye approved these changes
Looks good other than the above comment from @srambach.

Wondering if for the HTML implementation whether it'd make more sense to just add a level 3 heading to the "Documentation" section, more explicitly stating "In order to use a custom image do XYZ" (I imagine just giving the CSS var a new `url('...')` value).

Could also show an example, but that might require an example for the other components that use BackgroundImage internally.

2023-03-29 12:48 UTC, merged

2023-03-29 13:29 UTC, patternfly-build commented
:tada: This PR is included in version 5.0.0-alpha.37 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.37)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.0.0-alpha.37)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: