chore(base): remove breaking styles from _common.scss
patternfly/patternfly pull request #5339
Opened 2023-01-18 19:55 UTC by jenny-s51

Closes #5261

2023-01-18 20:02 UTC, patternfly-build commented
Preview: https://patternfly-pr-5339.surge.sh

2023-01-23 22:16 UTC, mcoker requested changes
so nice!!! one small change to remove a sass var we no longer need.

2023-01-23 22:16 UTC, mcoker commented on src/patternfly/base/_common.scss
> -@if $pf-global--unset-root-font-size {
we can also remove this https://github.com/patternfly/patternfly/blob/14e45911682ee81e822cecc02c22cb380a98c05b/src/patternfly/sass-utilities/scss-variables.scss#L15

2023-01-24 21:16 UTC, jenny-s51 reviewed
Thank you @mcoker ! Updated 🙂

2023-01-24 21:46 UTC, mcoker approved these changes
nice 😎

2023-01-24 21:46 UTC, merged

2023-01-25 00:50 UTC, patternfly-build commented
:tada: This PR is included in version 5.0.0-alpha.8 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.8)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.0.0-alpha.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: