Refactor input group 4003
patternfly/patternfly pull request #5382
Opened 2023-02-14 12:42 UTC by mattnolting

closes #4003

2023-02-14 12:46 UTC, patternfly-build commented
Preview: https://patternfly-pr-5382.surge.sh

2023-02-15 03:06 UTC, mcoker requested changes
Left some comments, lemme know what you think. Also the item handlebars file is impressive but a bit complicated so I didn't review it in detail. Two considerations on that:
* I don't want the complexity there to hold up merging this if we can avoid it. Either in dev or reviews. So we can be flexible there in whatever way makes the most sense.
* I wonder if instead of `--index` we have `--id` on the parent and items that need it. That would allow us to do `button--id=(concat "button-" input-group--id input-group-item--id)`, which it doesn't look like we can do now. Also it's just more consistent, so it's (maybe?) easier to work with.

2023-02-15 12:39 UTC, mattnolting commented on src/patternfly/components/InputGroup/input-group.scss
> +  align-items: stretch;
Yes, for the buttons and text to size appropriately 

**With flex**

<img width="630" alt="Screenshot 2023-02-15 at 7 38 38 AM" src="https://user-images.githubusercontent.com/5385435/219029613-bb823559-be2d-4ee1-b2d8-b2b535ccf439.png">

**Without flex**

<img width="612" alt="Screenshot 2023-02-15 at 7 38 47 AM" src="https://user-images.githubusercontent.com/5385435/219029735-d4e87db0-630d-4fee-b7df-62fc4c57ee0c.png">

2023-02-15 20:18 UTC, mcoker reviewed
LGTM, just a handful of nits.

2023-02-15 20:18 UTC, mcoker commented on src/patternfly/components/InputGroup/examples/InputGroup.md
> +    {{/input-group-text}}
should you update this to match the others?

```suggestion
    {{> input-group-text input-group-text--value="@example.com" input-group-text--attribute='id="email-example"'}}
```

2023-02-15 20:18 UTC, mcoker commented on src/patternfly/components/InputGroup/examples/InputGroup.md
> +    {{/input-group-text}}
```suggestion
    {{> input-group-text input-group-text--value="%"}}
```

2023-02-15 20:18 UTC, mcoker commented on src/patternfly/demos/Masthead/examples/Masthead.md
> +
```suggestion
```

2023-02-15 20:18 UTC, mcoker commented on src/patternfly/components/InputGroup/examples/InputGroup.md
> +    {{> input-group-text input-group-text--HasDollarSignIcon=true input-group-text--IsGray=true}}
```suggestion
    {{> input-group-text input-group-text--HasDollarSignIcon=true}}
```

2023-02-15 20:18 UTC, mcoker commented on src/patternfly/components/InputGroup/examples/InputGroup.md
> +    {{> input-group-text input-group-text--value=".00" input-group-text--IsGray=true}}
```suggestion
    {{> input-group-text input-group-text--value=".00"}}
```

2023-02-15 20:18 UTC, mcoker commented on src/patternfly/components/InputGroup/examples/InputGroup.md
> +    {{> input-group-text input-group-text--HasAtIcon=true input-group-text--IsGray=true}}
```suggestion
    {{> input-group-text input-group-text--HasAtIcon=true}}
```

2023-02-15 22:09 UTC, mcoker commented on src/patternfly/components/InputGroup/input-group.scss
> +  align-items: stretch;
Oh sorry, I meant `align-items` since it's the default value. But looks like you removed it!

2023-02-15 22:10 UTC, mcoker approved these changes
🚀

2023-02-16 23:57 UTC, mcoker approved these changes
🚀

2023-03-01 16:48 UTC, srambach commented
Now I can resize the text area in unexpected ways - before you could only make it taller or shorter, and you could get it just slightly shorter than the button. But you couldn't make it wider or narrower. Is this desired?

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/19825616/222206216-ef078f65-5b00-48ac-b5e1-9d6976b8c45a.png">

2023-03-02 17:48 UTC, mattnolting commented
@srambach new issue here https://github.com/patternfly/patternfly/issues/5407

> Now I can resize the text area in unexpected ways - before you could only make it taller or shorter, and you could get it just slightly shorter than the button. But you couldn't make it wider or narrower. Is this desired?
> 
> <img alt="image" width="1216" src="https://user-images.githubusercontent.com/19825616/222206216-ef078f65-5b00-48ac-b5e1-9d6976b8c45a.png">

Looks like this issue already exists for `pf-c-form-control` 

<img width="1034" alt="Screenshot 2023-03-02 at 11 33 18 AM" src="https://user-images.githubusercontent.com/5385435/222509405-a48dbbb3-e740-4d50-a40f-cdebc409e4e8.png">

2023-03-03 23:26 UTC, mcoker commented
Looks like there is a CSS lint error - rebasing v5 should fix it.

2023-03-14 21:08 UTC, srambach commented
> @srambach new issue here #5407
> 
> > Now I can resize the text area in unexpected ways - before you could only make it taller or shorter, and you could get it just slightly shorter than the button. But you couldn't make it wider or narrower. Is this desired?
> > <img alt="image" width="1216" src="https://user-images.githubusercontent.com/19825616/222206216-ef078f65-5b00-48ac-b5e1-9d6976b8c45a.png">
> 
> Looks like this issue already exists for `pf-c-form-control`
> 
> <img alt="Screenshot 2023-03-02 at 11 33 18 AM" width="1034" src="https://user-images.githubusercontent.com/5385435/222509405-a48dbbb3-e740-4d50-a40f-cdebc409e4e8.png">

Also, in a text input group, the text input shouldn't resize to be shorter than the accompanying buttons. I added that to the other issue.

2023-03-14 21:09 UTC, srambach approved these changes
Approve with follow on issue for resizing.

2023-03-15 12:54 UTC, merged

2023-03-15 13:06 UTC, patternfly-build commented
:tada: This PR is included in version 5.0.0-alpha.32 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.32)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.0.0-alpha.32)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: