fix(global): rename default status color to custom
patternfly/patternfly pull request #5418
Opened 2023-03-08 16:49 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/5175

Also makes a status variation required for the alert component. Previously the alert with no variant would give you the "default", aka "custom" status styling. Now the alert without a variation is unstyled and you have to add `.pf-m-custom`.

2023-03-08 16:53 UTC, patternfly-build commented
Preview: https://patternfly-pr-5418.surge.sh

2023-03-13 13:39 UTC, thatblindgeye requested changes

2023-03-13 13:39 UTC, thatblindgeye commented on src/patternfly/components/Alert/alert.scss
> +    --pf-c-alert--m-inline--BackgroundColor: var(--pf-c-alert--m-inline--m-custom--BackgroundColor);
Doesn't look like `--pf-c-alert--m-inline--m-custom--BackgroundColor` is defined anywhere

2023-03-13 13:39 UTC, thatblindgeye commented on src/patternfly/components/Popover/popover-title-text.hbs
>          Default
Similar to above, would we want this text to be "Custom" instead?

2023-03-13 17:22 UTC, thatblindgeye reviewed
Looks good! Only other thing is the screenshot for the "custom alert popover" example needs to be updated.

2023-03-13 17:31 UTC, mcoker commented
@thatblindgeye great catches! The full-page example screenshots are updated prior to a release, usually with the versioned commit that adds the release notes. Though you can run the job and push to this PR if you'd like! The instructions are at https://github.com/patternfly/patternfly/#update-screenshots Note that it may update more screenshots than this one since that job isn't run with each change and there have been a lot of changes since the last run.

2023-03-15 20:10 UTC, srambach commented on src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md
Line 127 - Should add '.pf-m-custom' as an acceptable modifier (or just remove the list and simply say always to use it with a state modifier)

2023-03-20 13:59 UTC, srambach approved these changes
:+1 LGTM

2023-03-21 01:18 UTC, merged

2023-03-21 01:34 UTC, patternfly-build commented
:tada: This PR is included in version 5.0.0-alpha.34 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.34)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.0.0-alpha.34)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: