feat(helper-text): make icon required for status
patternfly/patternfly pull request #5443
Opened 2023-03-27 20:59 UTC by srambach

Fixes #5438 

Whenever there is a status on helper text, it now adds the icon in the handlebars.
Removes `helper-text--HasIcon` in uses of helper-text where there is already a status specified, as it is no longer needed
Removes the separate example in Form.md for helper text with an icon, since it's always there
In FormControl.md, the explanatory text at the beginning is updated, but the examples do not include the helper text, but points to the Form examples to show how.

2023-03-27 21:04 UTC, patternfly-build commented
Preview: https://patternfly-pr-5443.surge.sh

2023-03-28 20:03 UTC, thatblindgeye requested changes
In addition to the file comments below:

- There are a couple of template files in the demos/Alert directory (horizontal-form and stacked-form) where helper-text-item--HasIcon should be able to be removed (something like IsError is being passed to trigger the icon already)
- For the "Dynamic" and "Dynamic lists" examples for HelperText, the helper-text-item--HasIcon should be able to be removed

2023-03-31 14:29 UTC, thatblindgeye approved these changes

2023-04-11 20:34 UTC, srambach commented
Closing in favor of a new approach to keep icons in the form controls. https://github.com/patternfly/patternfly/issues/5469

2023-04-11 20:34 UTC, closed without merging