chore(SearchInput): removed component
patternfly/patternfly pull request #5506
Opened 2023-04-21 12:48 UTC by thatblindgeye

Closes #5212

2023-04-21 12:54 UTC, patternfly-build commented
Preview: https://patternfly-pr-5506.surge.sh

2023-05-10 15:59 UTC, mcoker requested changes
LGTM! Couple of nits:

* Looks like we need to remove https://github.com/patternfly/patternfly/blob/246534b256b958d487f003b6da86c8e526e49363/src/patternfly/sass-utilities/component-namespaces.scss#L206-L207
* I don't think any of these `#ws-core-c-search-input[...]` id's exist anywhere in the text input group docs? https://github.com/patternfly/patternfly/blob/v5/src/patternfly/components/TextInputGroup/examples/TextInputGroup.css

2023-05-10 18:08 UTC, srambach approved these changes
lgtm. Created an issue for a masthead demo where the search input is displaying incorreclty outside the masthead, but that exists in the demo already. (https://github.com/patternfly/patternfly/issues/5557)

2023-05-10 23:25 UTC, mcoker approved these changes
💪

2023-05-10 23:26 UTC, merged

2023-05-10 23:42 UTC, patternfly-build commented
:tada: This PR is included in version 5.0.0-alpha.50 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.50)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.0.0-alpha.50)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: