Combine Label and Label Group docs
patternfly/patternfly pull request #5544
Opened 2023-05-08 20:46 UTC by mcarrano

2023-05-08 20:50 UTC, patternfly-build commented
Preview: https://patternfly-pr-5544.surge.sh

2023-05-10 20:05 UTC, srambach approved these changes
LGTM

2023-05-11 01:34 UTC, mcoker requested changes

2023-05-11 01:34 UTC, mcoker commented on src/patternfly/components/Label/examples/Label.md
> +### Basic label grouo
```suggestion
### Basic label group
```

2023-05-11 01:34 UTC, mcoker reviewed
LGTM!

2023-05-11 01:34 UTC, merged