fix(toolbar): fixed vertical alignment issue
patternfly/patternfly pull request #5565
Opened 2023-05-16 10:25 UTC by mattnolting

closes #5532

Apparently Firefox calculates baseline differently than other browsers. 

Here's an example including this update: https://codesandbox.io/s/relaxed-smoke-qfxw7r?file=/index.html

2023-05-16 10:32 UTC, patternfly-build commented
Preview: https://patternfly-pr-5565.surge.sh

2023-05-17 21:24 UTC, mcoker requested changes
Looks like this is still causing an issue in FF, and potentially introduced a new issue to chrome/safari - https://patternfly-pr-5565.surge.sh/components/toolbar/html-demos/toolbar-with-validation-on-desktop/

2023-05-18 21:33 UTC, mcoker approved these changes
This seems to fix the alignment issues! 

A couple of thoughts:
* Do you want to update the item alignment classes in the same manner? https://github.com/patternfly/patternfly/blob/3925ac563a360c1ef8356246d4865ac6b198baaf/src/patternfly/components/Toolbar/toolbar.scss#L315-L321
* It's getting very flex-layout-ey but the reason we have `.pf-m-align-[items/self]-baseline`, even though the default was already baseline, was if you applied `.pf-m-align-[items/self]-center` to a _thing_, and you wanted some of the _things in that thing_ to maintain their default/baseline alignment, we provide a class for that. Now that the default is `flex-start`, should we provide a `.pf-m-align-flex-start` on things for when you use baseline/center on the thing's parent?

2023-05-19 02:07 UTC, mattnolting commented
@mcoker updated the fix. Added `align-self/items: flex-start/center/baseline` to flexbox elements and `align-self: flex-start/center/baseline` to non-flexbox (`toolbar__item`s).

2023-05-25 18:52 UTC, mcoker approved these changes
LPTM! One nit, I'd rename the `flex-start` modifier classes to `start` - we'll move there eventually as we have full browser support for removing `flex-` from those logical values, and the modifier name doesn't tie us through the wording in the name to a flex layout. We can switch to grid or whatever, and "start" will still mean the start of whatever direction it flows. wdyt?

2023-05-25 19:21 UTC, mattnolting commented
@mcoker updated!

2023-05-25 20:09 UTC, mcoker approved these changes

2023-05-25 20:10 UTC, merged

2023-05-25 20:22 UTC, patternfly-build commented
:tada: This PR is included in version 5.0.0-alpha.66 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.66)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.0.0-alpha.66)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: