fix(form-control): fixed dark theme readonly/disabled styles
patternfly/patternfly pull request #5628
Opened 2023-05-26 07:00 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/5627

2023-05-26 07:07 UTC, patternfly-build commented
Preview: https://patternfly-pr-5628.surge.sh

2023-05-26 15:10 UTC, mcarrano requested changes
@mcoker this looks much better now. Just one small problem. The Read-only field should retain the bottom border like other fields (except disabled). It does in light theme but not visible in dark.

@andrew-ronaldson and @mceledonia can you also take a look?

2023-05-31 12:29 UTC, andrew-ronaldson approved these changes
LGTM @mcoker

2023-05-31 19:49 UTC, thatblindgeye approved these changes

2023-05-31 21:55 UTC, merged

2023-05-31 22:12 UTC, patternfly-build commented
:tada: This PR is included in version 5.0.0-alpha.71 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.0.0-alpha.71)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.0.0-alpha.71)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: