fix(core): darkened circle icon to match dark theme
patternfly/patternfly pull request #5651
Opened 2023-06-07 14:38 UTC by ashley-o0o

Adjusted the disabled switch in dark mode so that the colors match the other dark mode switches. Also added extra switches to include option with check.
<img width="456" alt="Screenshot 2023-06-07 at 10 30 48 AM" src="https://github.com/patternfly/patternfly/assets/123661468/431623f8-2930-4f1b-881c-c28c3a17514a">

Closes https://github.com/patternfly/patternfly/issues/5622

2023-06-07 14:40 UTC, ashley-o0o commented
What: Closes [#5622 ](https://github.com/patternfly/patternfly/issues/5622)

2023-06-07 14:45 UTC, patternfly-build commented
Preview: https://patternfly-pr-5651.surge.sh

2023-06-07 23:46 UTC, mcoker requested changes
Good job on this! This matches the check and the circle, but like we discussed offline, it's probably best if we retain the disabled color of the circle and update the check to match.

Because we're looking to get this in ASAP, the way I would probably go about this would be to:
* Declare a new variable at the end of this list for the check icon that we will use to manipulate the color of the check icon when the switch is in the disabled state, and give it the same value as the disabled circle color  https://github.com/patternfly/patternfly/blob/2f153a8479371d82b6e547b0e66ff322333bad02/src/patternfly/components/Switch/switch.scss#L9-L13
  * new variable - `--#{$switch}__input--disabled__toggle-icon--Color: var(--#{$pf-global}--palette--black-150);`
* In this disabled CSS block, in between the switch toggle selector and `cursor` declaration, add a new declaration for the check icon color to be defined by the disabled icon variable we defined in the previous step (Just a nit - you probably need an empty line after the new variable and the `cursor` declaration) https://github.com/patternfly/patternfly/blob/2f153a8479371d82b6e547b0e66ff322333bad02/src/patternfly/components/Switch/switch.scss#L123-L124 
  * new declaration - `--#{$switch}__toggle-icon--Color: var(--#{$switch}__input--disabled__toggle-icon--Color);`
* In the dark theme stylesheet, add a new declaration for the disabled check icon color that matches the disabled circle color https://github.com/patternfly/patternfly/blob/2f153a8479371d82b6e547b0e66ff322333bad02/src/patternfly/components/Switch/themes/dark/switch.scss#L4-L9
  * new declaration - `--#{$switch}__input--disabled__toggle-icon--Color: var(--#{$pf-global}--disabled-color--100);`

2023-06-07 23:46 UTC, mcoker commented on src/patternfly/components/Switch/examples/Switch.md
> +  {{#> switch-input switch-input--id="switch-with-icon-1" switch-input--attribute='disabled checked'}}{{/switch-input}}
The value here needs to match the value in the `for` attribute above.

```suggestion
  {{#> switch-input switch-input--id="switch-with-icon-disabled-1" switch-input--attribute='disabled checked'}}{{/switch-input}}
```

2023-06-07 23:46 UTC, mcoker commented on src/patternfly/components/Switch/examples/Switch.md
> +  {{#> switch-input switch-input--id="switch-with-icon-2" switch-input--attribute='disabled'}}
Same here - this needs to match the `for` attribute above

```suggestion
  {{#> switch-input switch-input--id="switch-with-icon-disabled-2"" switch-input--attribute='disabled'}}
```

2023-06-08 17:20 UTC, mcoker approved these changes
LGTM!

2023-06-08 17:41 UTC, mceledonia approved these changes

2023-06-08 17:58 UTC, mattnolting approved these changes
LPTM 👍

2023-06-08 18:09 UTC, merged

2023-08-08 19:28 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.1 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.1)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: