fix(form-control): fix disabled placeholder color
patternfly/patternfly pull request #5752
Opened 2023-07-11 13:47 UTC by srambach

Add `pf-m-placeholder` to a disabled [form control](https://patternfly-pr-5752.surge.sh/components/forms/form-control#select) to test.
This also removes the color set on the child of a select - this didn't seem to do anything anywhere so please comment if you know the original purpose of this.

Fixes #5629

2023-07-11 13:52 UTC, patternfly-build commented
Preview: https://patternfly-pr-5752.surge.sh

2023-07-31 17:14 UTC, thatblindgeye approved these changes

2023-07-31 21:49 UTC, mcoker commented on src/patternfly/components/FormControl/form-control.scss
> +    }
Another way you could do this is define the placeholder color when disabled.

```diff
diff --git a/src/patternfly/components/FormControl/form-control.scss b/src/patternfly/components/FormControl/form-control.scss
index 6d8e95996..a5bd1b2a2 100644
--- a/src/patternfly/components/FormControl/form-control.scss
+++ b/src/patternfly/components/FormControl/form-control.scss
@@ -206,6 +206,7 @@
   &.pf-m-disabled {
     --#{$form-control}--BackgroundColor: var(--#{$form-control}--m-disabled--BackgroundColor);
     --#{$form-control}--Color: var(--#{$form-control}--m-disabled--Color);
+    --#{$form-control}--m-placeholder--Color: var(--#{$form-control}--m-disabled--Color);
     --#{$form-control}__toggle-icon--Color: var(--#{$form-control}--m-disabled__toggle-icon--Color);
     --#{$form-control}--before--BorderStyle: none;
     --#{$form-control}--after--BorderStyle: none;
```

2023-08-02 19:39 UTC, mcoker requested changes
Just one small nit

2023-08-02 19:39 UTC, mcoker commented on src/patternfly/components/FormControl/form-control.scss
> +  }
nit - looks like some extra whitespace was added here

```suggestion
    }
  }
```

2023-08-03 14:08 UTC, mcoker approved these changes
🎃👍

2023-08-03 14:08 UTC, merged

2023-08-08 16:19 UTC, patternfly-build commented
:tada: This PR is included in version 5.1.0-prerelease.5 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.1.0-prerelease.5)
- [npm package (@prerelease dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.1.0-prerelease.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-08 19:27 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.1 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.1)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: