fix(wizard): added RTL styles
patternfly/patternfly pull request #5860
Opened 2023-08-24 21:35 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/5839

2023-08-24 21:40 UTC, patternfly-build commented
Preview: https://patternfly-pr-5860.surge.sh

2023-08-25 13:29 UTC, thatblindgeye requested changes
This looks nice 💪🏼

For the Wizard expandable icon, I'd expect that when collapsed it would be facing to the left when rtl is enabled. By default we have the nav link text followed by the toggle icon facing right (away from the link text), but with RTL enabled we have the toggle icon facing right (towards the link text) followed by the link text. This would follow how the tree view dual list selector is styled, where the icon is facing towards the item text in both LTR and RTL.

Can we just add in the `@include pf-v5-rtl("flip-inline");` in the nav-link-toggle-icon block around line ~536 to resolve that?

2023-08-25 13:29 UTC, thatblindgeye commented on src/patternfly/sass-utilities/mixins.scss
> +  @at-root :where(.ws-dir-rtl, .#{$pf-prefix}m-dir-rtl, [dir="rtl"]) & {
Checked and looks to work well when applying `dir` attribute, `ws-dir-rtl` class, and the modifier class to either the `html` tag or the base component tag 👍🏼

2023-08-25 16:01 UTC, mcoker commented
@thatblindgeye nice find, updated!

2023-08-25 17:13 UTC, wise-king-sullyman commented
It looks like the `of`s in pagination are off? 
<img width="371" alt="image" src="https://github.com/patternfly/patternfly/assets/7115053/e95bdd5b-d445-451d-8532-a8834264e025">

2023-08-25 17:18 UTC, wise-king-sullyman commented
Also no idea if this is actually an issue, but it's interesting to me that the text itself doesn't change, but the period moves around in the text here. Is that expected? 
<img width="649" alt="image" src="https://github.com/patternfly/patternfly/assets/7115053/eab8c7b8-33e3-471c-8705-680aa045b314">

2023-08-25 17:19 UTC, thatblindgeye approved these changes
🚀 Only have a nit below, but ti isn't blocking for this PR.

2023-08-25 17:19 UTC, thatblindgeye commented on src/patternfly/sass-utilities/mixins.scss
> +  @if $transform == "transform-flip-revert" {
Only nit is the naming of this particular value. Just wondering if "transform-flip(-revert)" conveys exactly what it's for, or if it's too close to "flip-inline"... "transform-modifier(-revert)" or "transform-multiplier(-revert)" maybe?

2023-08-25 17:26 UTC, thatblindgeye commented
@wise-king-sullyman I feel like those are expected? If I render just the text `Lorem ipsum.` or `1-10 of 36` in a plain div, applying rtl to it it's the same result.

2023-08-25 17:27 UTC, mcoker commented
> Also no idea if this is actually an issue, but it's interesting to me that the text itself doesn't change, but the period moves around in the text here. Is that expected? <img alt="image" width="649" src="https://user-images.githubusercontent.com/7115053/263346710-eab8c7b8-33e3-471c-8705-680aa045b314.png">

@wise-king-sullyman I noticed that, too, and it appears to just be the way punctuation is handled between LTR/RTL. I don't think there's anything we can do about that, and I think it changes based on your language.

2023-08-25 17:41 UTC, mcoker commented
> It looks like the `of`s in pagination are off? <img alt="image" width="371" src="https://user-images.githubusercontent.com/7115053/263345689-e95bdd5b-d445-451d-8532-a8834264e025.png">

Since those are just strings in core, I think that would look right in the correct language.

2023-08-25 17:47 UTC, thatblindgeye commented
Granted I'm viewing it after having the page translated to English, but when I go to the BBC site for Arabic, things look similar there where the punctuation is at the "start" (to us), and instead of "6 hours ago" an article reads "hours ago 6" (which would align to the Pagination x of y text).

2023-08-25 18:07 UTC, mattnolting approved these changes
Let's merge.

2023-08-25 18:07 UTC, merged

2023-08-25 18:20 UTC, patternfly-build commented
:tada: This PR is included in version 5.1.0-prerelease.9 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.1.0-prerelease.9)
- [npm package (@prerelease dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.1.0-prerelease.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: