chore(Alert,NotificationDrawer): added additional rtl styling
patternfly/patternfly pull request #5866
Opened 2023-08-28 13:54 UTC by thatblindgeye

Closes #5817 
closes #5818 

For both Alert and Notification drawer, the truncation is slightly different between Chromium and Firefox when viewing an example in a new window (viewing the examples normally on the component page things like fine). In Chromium a line clamp of 1 seems to cause the first word to be cut off, while a line clamp greater than 1 seems to truncate okay (same screenshot from the alert/hint issue linked above):

![Alert title truncation with RTL direction in Chrome](https://github.com/patternfly/patternfly/assets/70952936/941e40d3-a209-4f8a-8a51-466c6e6121b1)

In Firefox, it seems to be the reverse; line clamp of 1 truncates okay, while line clamp greater than 1 causes the first word of the last line to be cut off:

![Alert title truncation with RTL direction in Firefox](https://github.com/patternfly/patternfly/assets/70952936/76be7e09-c118-4745-827e-89ec66002273)

Since it seems to more have this affect if the Alert is wide enough it may not be a huge issue. This could also just be an issue with the Core examples, as applying `dir="rtl"` to the `html` tag in the React example the truncation looks fine (though that was also without any of the other RTL styling updates from Core).

2023-08-28 14:00 UTC, patternfly-build commented
Preview: https://patternfly-pr-5866.surge.sh

2023-08-28 22:09 UTC, mcoker commented
Hmm... I'm probably missing something, but these examples between chrome and firefox look the same to me:

<img width="1376" alt="Screenshot 2023-08-28 at 5 05 21 PM" src="https://github.com/patternfly/patternfly/assets/35148959/c9a4d65c-df27-4b91-9dcb-9eca760038f4">


<img width="1394" alt="Screenshot 2023-08-28 at 5 05 42 PM" src="https://github.com/patternfly/patternfly/assets/35148959/a52f308c-2740-44fd-9c11-a240c192b0a4">

2023-08-28 22:10 UTC, mcoker requested changes
LGTM! Just need to rebase and update to the new mixin name.

2023-08-28 22:10 UTC, mcoker commented on src/patternfly/components/Alert/alert.scss
> +  @include pf-v5-rtl('flip-inline');
```suggestion
  @include pf-v5-mirror-inline-on-rtl;
```

2023-08-28 22:10 UTC, mcoker commented on src/patternfly/components/NotificationDrawer/notification-drawer.scss
> +  @include pf-v5-rtl('flip-inline');
```suggestion
  @include pf-v5-mirror-inline-on-rtl;
```

2023-08-29 12:27 UTC, thatblindgeye commented
@mcoker Ah yep, it's because I have my browsers at an increased default zoom level. Lowering both to 100% results in similar truncation between the two.

2023-08-29 15:32 UTC, mcoker approved these changes
🚀

2023-08-30 18:02 UTC, srambach commented
FWIW, this has the same deal as I'm seeing on the card expansion toggle icon - it spins when going from LTR to RTL because of the transition timing provided for the rotation. If we can't find a workaround quickly, I think we should move ahead as is and follow up with a fix for all these cases.

2023-08-30 18:03 UTC, srambach approved these changes
Looks good - just the one comment about the transition timing causing an extra little flip.

2023-08-30 19:18 UTC, merged

2023-08-30 19:53 UTC, patternfly-build commented
:tada: This PR is included in version 5.1.0-prerelease.13 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.1.0-prerelease.13)
- [npm package (@prerelease dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.1.0-prerelease.13)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: