fix(toolbar): fix expand all icon in RTL
patternfly/patternfly pull request #5937
Opened 2023-09-15 15:05 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/5936

2023-09-19 14:24 UTC, thatblindgeye requested changes

2023-09-19 19:06 UTC, mcoker commented on src/patternfly/components/Toolbar/toolbar-expand-all-icon.hbs
> +  {{#> icon-content}}<span class="{{pfv}}toolbar__expand-all-icon{{#if toolbar-expand-all-icon--modifier}} {{toolbar-expand-all-icon--modifier}}{{/if}}"
@thatblindgeye ah thanks! I added a prop/param to the icon hbs in this PR (https://github.com/patternfly/patternfly/pull/5924) that will add the mirror-inline class in the right spot. If we can merge that one, I'll update this PR to use that.

2023-09-20 12:13 UTC, thatblindgeye approved these changes

2023-09-20 14:34 UTC, merged

2023-09-20 14:47 UTC, patternfly-build commented
:tada: This PR is included in version 5.1.0-prerelease.31 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v5.1.0-prerelease.31)
- [npm package (@prerelease dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.1.0-prerelease.31)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: