fix(input): standardized check and radio alignment
patternfly/patternfly pull request #5947
Opened 2023-09-19 15:13 UTC by mattnolting

closes #5802 

**Quicklinks:**
Checkbox: https://patternfly-pr-5947.surge.sh/components/forms/checkbox/
Radio: https://patternfly-pr-5947.surge.sh/components/forms/radio

**Still in flight:** 
[Table checkbox alignment ](https://patternfly-pr-5947.surge.sh/components/table#checkboxes-and-actions-example)

2023-09-19 15:14 UTC, patternfly-build commented
Preview: https://patternfly-pr-5947.surge.sh

2023-09-20 01:18 UTC, mcoker reviewed
Check and radio examples look spot on! Great job with that. Looks like just the standalone variation is left.

Were you planning on adding the form element toolbar item in this PR or is that just for testing?

2023-09-20 14:04 UTC, mattnolting commented
> Check and radio examples look spot on! Great job with that. Looks like just the standalone variation is left.

@mcoker standalone updated

> 
> Were you planning on adding the form element toolbar item in this PR or is that just for testing?

@mcoker I think it best to include form element toolbar item in this PR, but I can also put in a followup

2023-09-26 15:44 UTC, srambach commented
Looking good. I think the formula is solid.

2023-09-26 16:37 UTC, mcoker requested changes
L🎃TM except removing the inline display of the standalone variation, which I think we need - at least for the time being so that it isn't breaking.

2023-09-26 16:37 UTC, mcoker commented on src/patternfly/components/Check/check.scss
> + // find height of single label, divide by two, offset by 50% of own height
```suggestion
  // find height of single label, divide by two, offset by 50% of own height
```

2023-09-26 16:37 UTC, mcoker commented on src/patternfly/components/Check/check.scss
> -    display: inline-grid;
Removing this will break being able to put things before/after it inline

2023-10-06 01:17 UTC, mcoker approved these changes
LGTM

2023-10-09 15:18 UTC, srambach commented on src/patternfly/components/Toolbar/examples/Toolbar.md
> +| `.pf-m-form-element` | `.pf-v5-c-toolbar__item` | Initiates form element vertical positioning. |
Stupid nit, but can you change "initiates" to "Modifies for" or whatever makes sense grammatically? (maybe the ones below too?)

2023-10-09 15:20 UTC, srambach approved these changes
Just the one nit about the documentation, which isn't absolutely necessary. Nice improvement ❇️

2023-10-10 15:14 UTC, srambach approved these changes
👍

2023-10-10 15:21 UTC, merged

2024-02-28 22:41 UTC, patternfly-build commented
:tada: This PR is included in version 5.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/patch-v5.2.0)
- [npm package (@prerelease-bugfix dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-05-01 14:57 UTC, patternfly-build commented
:tada: This PR is included in version 5.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/patch-v5.3.0)
- [npm package (@prerelease-bugfix dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: