chore(masthead ): applied tokens
patternfly/patternfly pull request #6004
Opened 2023-10-17 14:26 UTC by mattnolting

closes #5712

2023-10-17 16:06 UTC, srambach reviewed
I'd love a run through to process the hbs changes.

2023-10-18 19:32 UTC, mcoker requested changes
Just a couple o' small changes, and it's worth noting that the designs have a bit different padding, maybe something we can look at later.

2023-10-18 19:32 UTC, mcoker commented on src/patternfly/components/Masthead/masthead-logo.hbs
> +<svg height="36px" viewBox="0 0 679 158" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```suggestion
<svg height="36px" viewBox="0 0 679 158" role="img">
```

2023-10-18 19:32 UTC, mcoker commented on src/patternfly/components/Masthead/masthead-logo.hbs
> +  <title>PF-HorizontalLogo-Color </title>
This should probably be similar to whatever the `alt` attribute would be 

```suggestion
  <title>Patternfly logo</title>
```

2023-10-18 19:34 UTC, mcoker approved these changes

2023-10-18 19:34 UTC, merged

2023-10-24 19:08 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.10 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.10)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-01-14 14:40 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.61 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.61)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.61)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: