feat(text, title, list): apply tokens
patternfly/patternfly pull request #6031
Opened 2023-11-02 21:23 UTC by srambach

Fixes #5730 

PR right before vacation so... 🤪 

Also adds modifiers for heading styles to the title component.

2023-11-02 21:27 UTC, patternfly-build commented
Preview: https://patternfly-pr-6031.surge.sh

2023-11-08 17:21 UTC, lboehling commented
thanks sarah! this is looking good. I do notice that the top level heading "hello world" in the text component doesn't seem to be pulling in the right size. 
<img width="873" alt="image" src="https://github.com/patternfly/patternfly/assets/46571616/c372e1d9-66f4-4ec6-a127-533bd8c39158">

2023-11-09 22:27 UTC, mcoker requested changes
LGTM, just one typo in a token name.

Also may be worth considering adding these as tokens and using them in the text/content component and for the title heading level variations

```
  --pf-t--global--font--size--heading--h1: var(--pf-t--global--font--size--heading--lg);
  --pf-t--global--font--size--heading--h2: var(--pf-t--global--font--size--heading--md);
  --pf-t--global--font--size--heading--h3: var(--pf-t--global--font--size--heading--sm);
  --pf-t--global--font--size--heading--h4: var(--pf-t--global--font--size--heading--xs);
  --pf-t--global--font--size--heading--h5: var(--pf-t--global--font--size--heading--xs);
  --pf-t--global--font--size--heading--h6: var(--pf-t--global--font--size--heading--xs);
```

2023-11-09 22:27 UTC, mcoker commented on src/patternfly/components/Title/title.scss
> +  --#{$title}--m-h2--FontSize: var(--pf-t--global--font--size--heading-md);
```suggestion
  --#{$title}--m-h2--FontSize: var(--pf-t--global--font--size--heading--md);
```

2023-11-10 19:42 UTC, mcoker approved these changes
👍👍

2023-11-10 20:14 UTC, merged

2023-11-10 20:23 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.16 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.16)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-01-14 14:40 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.61 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.61)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.61)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: