V6 rebase 11.8.23 2
patternfly/patternfly pull request #6048
Opened 2023-11-08 23:55 UTC by mcoker

2023-11-08 23:55 UTC, patternfly-build commented
Preview: https://patternfly-pr-6048.surge.sh

A11y report: https://patternfly-pr-6048-a11y.surge.sh

2023-11-09 13:25 UTC, thatblindgeye approved these changes

2023-11-13 13:57 UTC, mfrances17 requested changes
Looks like one merge conflict to address otherwise LGTM

2023-11-16 19:52 UTC, srambach approved these changes
this looks good on my spot checks.

2023-11-17 21:27 UTC, mfrances17 approved these changes
LGTM

2023-11-17 21:28 UTC, merged

2023-11-21 16:11 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.18 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.18)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-01-14 14:40 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.61 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.61)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.61)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-28 22:40 UTC, patternfly-build commented
:tada: This PR is included in version 5.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/patch-v5.2.0)
- [npm package (@prerelease-bugfix dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-05-01 14:57 UTC, patternfly-build commented
:tada: This PR is included in version 5.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/patch-v5.3.0)
- [npm package (@prerelease-bugfix dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/5.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: