feat(BackToTop): refactor with tokens
patternfly/patternfly pull request #6085
Opened 2023-11-28 22:11 UTC by wise-king-sullyman

Closes #6084

2023-11-28 22:15 UTC, patternfly-build commented
Preview: https://patternfly-pr-6085.surge.sh

2023-11-29 19:27 UTC, mcoker requested changes
Looks good! Left a couple o' comments for review

2023-11-29 19:27 UTC, mcoker commented on src/patternfly/components/BackToTop/back-to-top.scss
> +  --#{$back-to-top}--c-button--BoxShadow: var(--pf-t--global--box-shadow--lg--bottom);
Looks like the design calls for `/* light/global/shadow/small */`

2023-11-29 19:27 UTC, mcoker commented on src/patternfly/components/BackToTop/back-to-top.scss
> +  --#{$back-to-top}--c-button--BorderRadius: var(--pf-t--global--border--radius--large);
This uses the pill radius in design, but I think we can just remove this in favor of the pill radius on the button. I imagine the distinction between this button and the button component is just the font-size, padding, and box-shadow.

2023-11-29 20:00 UTC, andrew-ronaldson commented
Can we add `text-decoration: none` to remove the underline

2023-11-30 15:55 UTC, mcoker approved these changes
🤩

2023-11-30 16:38 UTC, andrew-ronaldson approved these changes
LGTM, thanks

2023-11-30 16:39 UTC, merged

2024-01-14 14:39 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.61 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.61)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.61)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: