6029 toggle group tokens
patternfly/patternfly pull request #6190
Opened 2024-01-05 21:34 UTC by srambach

Fixes #6029

2024-01-05 21:37 UTC, patternfly-build commented
Preview: https://patternfly-pr-6190.surge.sh

2024-01-06 11:40 UTC, andrew-ronaldson approved these changes
Matches Figma, LGTM for design!

2024-01-06 15:03 UTC, mattnolting requested changes
Outstanding! 👏👏👏 

Looks like you can drop 

[& + & {
  margin-inline-start: var(--#{$toggle-group}__item--item--MarginLeft);
}
](https://github.com/patternfly/patternfly/pull/6190/files#diff-045989b534efcabcb44e8d2fea279cb9b1242530cc45366f9980aee247064568R60-R63) per the design spec 🎉 

<img width="1050" alt="Screenshot 2024-01-06 at 9 57 33 AM" src="https://github.com/patternfly/patternfly/assets/5385435/b93501b3-65d6-4b16-b6b0-1a25f9bce5de">

2024-01-06 17:06 UTC, mattnolting commented
@andrew-ronaldson As a followup, we need to consider mobile presentation. Here's an example of toggle group items overflowing and how `toggle-group` can handle this scenario. 

<img width="365" alt="Screenshot 2024-01-06 at 11 04 36 AM" src="https://github.com/patternfly/patternfly/assets/5385435/cffd90a9-f775-4b6c-822a-3b56d18581fd">

**Things to consider**
- [ ] Adjacent selected item border. When textual content is less consistent, adjacent selected items appear run together. Should we include border updates here??
- [ ] When toggle items extend past toggle group boundaries, the overflow is currently hidden (default). If we move the border to `toggle-group` instead of items, we can drop top/bottom borders on individual items, and conditionally drop left/right border for `:first/:last-child`. This results in the content being scrollable while presenting design accurately. 
- [ ] When `toggle-group` is a child of `display: flex/grid` its width grows. Should add `width: min-content` to `toggle-group` as well as `white-space: nowrap` to `toggle-group__button`. 

**Toggle group as a child of `display: flex/grid`**

<img width="605" alt="Screenshot 2024-01-06 at 11 35 32 AM" src="https://github.com/patternfly/patternfly/assets/5385435/b1908ec8-e5e4-4f27-9d19-ec462630836a">

**Toggle group button set to `white-space: nowrap`**

<img width="379" alt="Screenshot 2024-01-06 at 11 33 30 AM" src="https://github.com/patternfly/patternfly/assets/5385435/dcb3a42d-10d0-4ba5-9dcf-0279c3642889">



https://codesandbox.io/p/sandbox/infallible-meadow-msz34w?file=%2Fstyle.css%3A12%2C111

2024-01-08 13:33 UTC, srambach commented on src/patternfly/components/ToggleGroup/toggle-group.scss
> +  --#{$toggle-group}__item--item--MarginLeft: calc(-1 * var(--pf-t--global--border--width--control--default));
@mattnolting Actually I checked with @andrew-ronaldson and they'd still like to collapse that down to 1px; it was just too complicated in Figma.

2024-01-08 13:54 UTC, mattnolting approved these changes
LPTM!

2024-01-09 14:30 UTC, srambach commented
Issue created to look at the mobile view as @mattnolting suggested. https://github.com/patternfly/patternfly/issues/6202

2024-01-12 15:18 UTC, lboehling commented
Looks good! I also +1 nolting's comment about including a border so that adjacent clicked items don't look like they're running together.

2024-01-12 15:19 UTC, kmcfaul approved these changes

2024-01-12 15:20 UTC, thatblindgeye approved these changes

2024-01-12 16:59 UTC, merged

2024-01-12 17:12 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.58 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.58)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.58)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: