feat(DragDrop): use tokens
patternfly/patternfly pull request #6204
Opened 2024-01-10 16:22 UTC by kmcfaul

Closes #5740

As design for penta drag and drop is still in flight (for both the current and new implementations) this PR updates the current styling to use the new tokens. A follow up may be required later if the design changes.

2024-01-10 16:26 UTC, patternfly-build commented
Preview: https://patternfly-pr-6204.surge.sh

2024-01-12 15:52 UTC, thatblindgeye reviewed
One issue I'm noticing is in dark mode the text blends in with the background for the dragged item:

![image](https://github.com/patternfly/patternfly/assets/70952936/23bb8e14-45b9-4068-b353-ec71d09b143c)

2024-01-12 16:37 UTC, andrew-ronaldson requested changes
Can you add a border radius  of` --pf-t--global--border--radius--small` on the drag item and the container please.

2024-01-12 17:15 UTC, thatblindgeye approved these changes

2024-01-12 18:49 UTC, andrew-ronaldson approved these changes
Totally Excellent!

2024-01-12 18:49 UTC, merged

2024-01-12 18:59 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.59 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.59)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.59)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: