feat(SimpleFileUpload): consumed Penta tokens
patternfly/patternfly pull request #6211
Opened 2024-01-11 16:40 UTC by thatblindgeye

Closes #6209 

- Removed usage of the form helper text since it seems like from the design the helper text should be tied to File Upload, not Form
- Added a helper text example that makes the text area aria label "Uploaded file content" and tied the helper text to the Upload button. Also made these updates to the "with error" example. As a follow up we should consider making similar changes to other examples, as well as:
  - possibly updating the text input aria label to "File name"; right now it just duplicates the placeholder or value attribute
  - remove the aria-describedby from the text input, as currently it being described by the upload button doesn't provide adequate description

For the "with error" example, is the intent that if a file upload has a type/size restriction, it must be placed in a Form component? Or is this example more like a demo of showing how one could place a file upload inside a form? Right now React only uses Form components for a similar "restrictive" example, but it would seem like a non-restrictive file upload could/should also be placed inside a Form for some sort of submission as well.

2024-01-11 16:44 UTC, patternfly-build commented
Preview: https://patternfly-pr-6211.surge.sh

2024-01-12 15:09 UTC, lboehling approved these changes
LGTM!!

2024-01-12 15:10 UTC, srambach approved these changes
🌟 Looks great to me

2024-01-12 15:11 UTC, andrew-ronaldson approved these changes
Happy happy joy joy!

2024-01-12 15:12 UTC, kmcfaul approved these changes

2024-01-12 15:24 UTC, mcoker requested changes
Just one nit!

2024-01-12 15:24 UTC, mcoker commented on src/patternfly/components/FileUpload/file-upload.scss
> +
If you rebase, I believe you can remove this now?

```suggestion
```

2024-01-12 17:01 UTC, mcoker approved these changes
🔥

2024-01-12 17:01 UTC, merged