fix(label): add status variants
patternfly/patternfly pull request #6227
Opened 2024-01-13 02:03 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/6226

2024-01-13 02:07 UTC, patternfly-build commented
Preview: https://patternfly-pr-6227.surge.sh

2024-01-13 12:10 UTC, andrew-ronaldson reviewed
Apologies if I missed a conversation. Should the status lables have the status color on the icon or is it just inheriting the colour from the text? In Figma the icons all have the status color. 

From a design guidelines perspective I think we should recommend using a status label with the icons so they stand out from the non status versions. @lboehling do you have any thoughts here?

2024-01-15 15:28 UTC, thatblindgeye reviewed
Unless it'd be better as a followup, can we update the status labels to use appropriate icons? Right now they're all using the info icon, when success should have a checkmark, warning the triangle `!`, etc.

2024-01-22 20:46 UTC, thatblindgeye commented on src/patternfly/components/Label/label--variants.hbs
> +      label-icon--value="info-circle"
Just a nit: since we're showing status labels that would use this icon, we might want to avoid using a "statusy" icon outside a status context. WdYT?

2024-01-24 13:38 UTC, thatblindgeye approved these changes
✅  As a followup we could add screen reader text to the status labels, but it might be worth evaluating where else we may want to do that in other components and/or if it makes sense to always render it vs rendering it only if the visible text doesn't convey that status well.

2024-01-24 13:50 UTC, andrew-ronaldson approved these changes
Rockstar. LGTM

2024-01-24 18:46 UTC, srambach approved these changes
LGTM. Kind of a bummer to have to require `.pf-m-filled` but makes sense. 🏷️

2024-01-24 20:01 UTC, lboehling requested changes
looks good! I am noticing that the filled background color for the status labels are referencing a border color token instead of the global/color/status/[success/danger/warning/etc.] tokens

2024-01-24 20:20 UTC, mcoker commented
@lboehling great catch!! Looks like all of the filled background color tokens were wrong 🤦‍♂️ Updated, you can see the tokens changed here - https://github.com/patternfly/patternfly/pull/6227/commits/ea51c909cf61e5b2ec91d319b07e6f26f4aaad88

FWIW I just did a search/replace for `--BackgroundColor: var(--pf-t--global--border--color` with `--BackgroundColor: var(--pf-t--global--color`

2024-01-24 23:04 UTC, lboehling commented
perfect! thanks @mcoker!!

2024-01-25 01:30 UTC, merged

2024-01-25 01:40 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.69 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.69)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.69)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: