fix(tree-view): add tokens
patternfly/patternfly pull request #6284
Opened 2024-02-08 02:56 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/5723

2024-02-08 03:00 UTC, patternfly-build commented
Preview: https://patternfly-pr-6284.surge.sh

2024-02-09 16:31 UTC, srambach approved these changes
I don't see any problems, good questions posed in the description. 🌴

2024-02-09 19:42 UTC, wise-king-sullyman requested changes

2024-02-09 19:42 UTC, wise-king-sullyman commented on src/patternfly/components/TreeView/tree-view.scss
> +  --#{$tree-view}__node-toggle-icon--MinWidth: var(--pf-t--global--icon--size--body--default);
Duplicate var?

2024-02-09 20:20 UTC, merged

2024-02-09 20:30 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.78 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.78)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.78)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: