fix(menu-toggle): updates for alpha
patternfly/patternfly pull request #6322
Opened 2024-02-15 01:38 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/6319

2024-02-15 01:41 UTC, patternfly-build commented
Preview: https://patternfly-pr-6322.surge.sh

2024-02-15 16:06 UTC, kmcfaul commented on src/patternfly/components/Menu/menu.scss
> +  &:focus-within,
I think we need `pf-m-focus` back for typeahead select to manually show visual focus on an item, because actual focus remains on the input.

2024-02-19 14:54 UTC, kmcfaul approved these changes

2024-02-26 15:41 UTC, mattnolting requested changes
Nice work, several version updates are needed for examples.

2024-02-26 15:41 UTC, mattnolting commented on src/patternfly/components/Menu/menu.scss
>    --pf-v5-c-check__input--TranslateY: none;
```suggestion
  --pf-v6-c-check__input--TranslateY: none;
```

2024-02-26 15:57 UTC, mattnolting approved these changes

2024-02-26 15:57 UTC, merged