fix(page): add container around main element
patternfly/patternfly pull request #6410
Opened 2024-03-11 19:46 UTC by srambach

This adds a container around the main element so that the border-rounding and other styling can be applied to the container, while the main element handles layout of the sections.

Fixes #6225

2024-03-11 19:49 UTC, patternfly-build commented
Preview: https://patternfly-pr-6410.surge.sh

2024-03-21 16:18 UTC, mcoker reviewed
Just one nit

2024-03-21 18:47 UTC, mcoker approved these changes

2024-03-21 18:56 UTC, mcoker requested changes
One more bit - now that `{{#> page-main}}` includes this globally, we can remove the container from this template https://github.com/patternfly/patternfly/blob/6ffe50d3b8697bd7cda6f05599d39ecff81567b7/src/patternfly/demos/Page/page-template-main.hbs#L1-L5

Also just to confirm, with a drawer in the page (like a [notification drawer](https://patternfly-pr-6410.surge.sh/components/drawer/html-demos/expanded/)) the grid area for the main page stuff is `.pf-c-page__drawer` which is not currently wrapped in the main-container - should it be, or is it good the way it is?

2024-03-21 20:33 UTC, srambach commented
> One more bit - now that `{{#> page-main}}` includes this globally, we can remove the container from this template
> 
if one is good, two are better, no? 🤪 
> https://github.com/patternfly/patternfly/blob/6ffe50d3b8697bd7cda6f05599d39ecff81567b7/src/patternfly/demos/Page/page-template-main.hbs#L1-L5
> 
> Also just to confirm, with a drawer in the page (like a [notification drawer](https://patternfly-pr-6410.surge.sh/components/drawer/html-demos/expanded/)) the grid area for the main page stuff is `.pf-c-page__drawer` which is not currently wrapped in the main-container - should it be, or is it good the way it is?
Hmmmmm. That would fix a problem where a drawer content with a background escapes the rounded corners, but also cause the drawer panel to be contained inside the rounded corners, which is not the intention I think.

2024-03-21 23:42 UTC, mcoker approved these changes

2024-03-21 23:42 UTC, merged

2024-03-21 23:49 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.104 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.104)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.104)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: