chore(Badge/MenuToggle): updated styling
patternfly/patternfly pull request #6543
Opened 2024-04-16 14:24 UTC by thatblindgeye

Closes #6463

2024-04-16 14:26 UTC, patternfly-build commented
Preview: https://patternfly-pr-6543.surge.sh

2024-04-30 16:00 UTC, andrew-ronaldson commented
The menu toggle example looks good here
<img width="305" alt="Screenshot 2024-04-30 at 12 52 48 PM" src="https://github.com/patternfly/patternfly/assets/28658548/a4170d67-ddf1-4b94-9280-448eab6d8527">

The breadcrumb example crops the hover/focus states to fit
<img width="815" alt="Screenshot 2024-04-30 at 12 53 44 PM" src="https://github.com/patternfly/patternfly/assets/28658548/30d3ad97-17ce-437a-8c29-a5e490c1467b"> 

is this caused by the breadcrumbs height?

2024-05-01 14:57 UTC, thatblindgeye commented
@andrew-ronaldson that's from setting the padding top/bottom on the MenuToggle in that particular instance to 0 to try and get it closer to being contained in the outer breadcrumb element. I can remove those style overrides which would result in the following:

![image](https://github.com/patternfly/patternfly/assets/70952936/64b02773-3493-4bfd-824e-8ab362c4ab36)
![image](https://github.com/patternfly/patternfly/assets/70952936/17e1c93c-72c8-48a8-8021-8e474c108726)

2024-05-14 13:42 UTC, thatblindgeye commented
@andrew-ronaldson Does this look more inline with what we'd want?

![image](https://github.com/patternfly/patternfly/assets/70952936/cbd8c648-7f25-4a77-87dd-60d63ebdef3c)

I updated the `--#{$breadcrumb}__dropdown--MarginInline[Start|End]` var to an xs spacer, instead of it creating a negative margin based on `calc(var(--#{$breadcrumb}__item--MarginInlineEnd) * -1)`

2024-05-14 17:10 UTC, andrew-ronaldson commented
Looks good with that update @thatblindgeye

2024-05-14 17:10 UTC, andrew-ronaldson approved these changes
looks dope!

2024-05-28 15:34 UTC, srambach approved these changes
🏅 Looks good to me.

2024-05-28 15:57 UTC, mcoker requested changes
Just one small nit!

2024-05-28 15:57 UTC, mcoker commented on src/patternfly/components/Breadcrumb/breadcrumb.scss
>    }
discussed in the working section that we can keep the padding as long as it it doesn't change the shape of the outer breadcrumb box. also looks like `line-height` is the same with or without this declaration, so I think we can nix this whole block!

2024-05-28 16:03 UTC, mcoker approved these changes

2024-06-03 16:01 UTC, merged

2024-06-03 16:09 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.148 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.148)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.148)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: