chore(menu-toggle): updated components to use menu toggle
patternfly/patternfly pull request #6566
Opened 2024-04-24 15:49 UTC by mattnolting

closes #6207

2024-04-24 15:53 UTC, patternfly-build commented
Preview: https://patternfly-pr-6566.surge.sh

2024-04-24 20:01 UTC, srambach reviewed
The menu on a menu toggle is showing up to the right 
<img width="1341" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/058544a8-3a9d-460d-8dc7-3afec40ebd33">

There seems to be a problem if the content is too wide?
<img width="539" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/4bfb0d0e-cb68-403c-b56e-b0de1493e198">

Various places I see the toggle scrunched up
<img width="857" alt="image" src="https://github.com/patternfly/patternfly/assets/19825616/8c6168fd-1183-4efd-aa3e-ea047af96abf">

2024-04-25 00:47 UTC, mcoker requested changes
[backstop report](https://github.com/patternfly/patternfly/files/15102011/backstop-4.24.24.pdf)

I'm sure some of these are known/purposeful since it's a WIP but since I've reviewed, IMO everything looks good  to merge except:
* The HBS helpers have console.logs that need to be removed
* The "New" menu example should be removed
* Overflow menu id's are broken, left a comment below on overflow.hbs

I'd like to merge this if possible so these examples are fixed. Currently they're throwing off the layout of lots of components (this visual regression report has 148 changes as result of this PR) and causing lots of issues with our screenshots. It would be great to fix those. If there is a different way of doing the hbs to make it more streamlined, that could always be done later and the visual regression tool can validate since it should(?) result in no visual changes. wdyt @srambach?

2024-04-25 00:47 UTC, mcoker commented on src/patternfly/components/Toolbar/toolbar-overflow-menu-example.hbs
> +      overflow-menu--id=(concat toolbar--id '-overflow-menu') menu--IsExpanded=toolbar-overflow-menu-example--IsExpanded
```suggestion
      overflow-menu--id=(concat toolbar--id '-overflow-menu')
      menu--IsExpanded=toolbar-overflow-menu-example--IsExpanded
```

2024-04-25 00:47 UTC, mcoker commented on src/patternfly/components/OverflowMenu/overflow-menu.hbs
> +  {{ternary overflow-menu--attribute 'id="{{overflow-menu--id}}"' ''}}>
ID's are broken

<img width="1373" alt="Screenshot 2024-04-24 at 7 35 51 PM" src="https://github.com/patternfly/patternfly/assets/35148959/02e0ee43-53fb-4c1b-9cd1-1c1d1c312f2f">

I'm assuming these 2 lines should be something like this instead?



```suggestion
  {{ternary overflow-menu--id 'id="' overflow-menu--id '"' ''}}
  {{ternary overflow-menu--attribute overflow-menu--attribute ''}}>
```

2024-04-25 16:06 UTC, mattnolting commented on src/patternfly/components/NotificationDrawer/notification-drawer.scss
> +
https://github.com/patternfly/patternfly/issues/6577

2024-04-26 00:54 UTC, mcoker requested changes

2024-04-26 12:36 UTC, mattnolting commented on src/patternfly/components/Menu/menu.scss
> +  --#{$menu}--MaxWidth: 400ch;
Menu has no `max-width` control. 

<img width="1078" alt="Screenshot 2024-04-26 at 8 36 11 AM" src="https://github.com/patternfly/patternfly/assets/5385435/8fb044a1-a088-4c41-afd2-c6c4f34738ae">

2024-05-03 18:25 UTC, mattnolting commented
[BackstopJS Report.pdf](https://github.com/patternfly/patternfly/files/15203693/BackstopJS.Report.pdf)

2024-05-14 19:10 UTC, srambach commented
OK - here's the report I just ran https://drive.google.com/file/d/1sIz7YyVqInrF6f8M2gjFTjjsjO_1_aR7/view?usp=sharing
The only significant differences I see are 
- Overflow menu doesn't go into the kebab on mobile http://localhost:5000/components/table/html/overflow-menu-usage-desktop/
- Selected filters lost icons http://localhost:5000/components/toolbar/html/selected-filters-on-desktop-not-responsive/
- Toolbar lost its icons http://localhost:5000/components/toolbar/html/stacked-on-desktop/

2024-05-14 20:30 UTC, mcoker approved these changes
LGTM! 🚀

2024-05-14 20:31 UTC, merged

2024-05-14 20:31 UTC, srambach approved these changes
🏇

2024-05-14 20:39 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.133 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.133)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.133)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: