chore(Wizard): resolved scroll issue and used ActionList for wizard buttons
patternfly/patternfly pull request #6611
Opened 2024-05-02 18:17 UTC by thatblindgeye

Closes #6314

2024-05-02 18:20 UTC, patternfly-build commented
Preview: https://patternfly-pr-6611.surge.sh

2024-05-15 20:24 UTC, mcoker requested changes
Nice! I think we can now update the footer just to be a regular box since the action list provides the button layout we need. We can take off all the flex stuff and child styling. Another thing to look for is the footer's bottom padding currently accounts for the bottom margin we're adding to children (buttons) in the footer, so that padding will likely need to be updated, too.

https://github.com/patternfly/patternfly/blob/c3f6c8175a7de2e643ec02102d32520b298e06ce/src/patternfly/components/Wizard/wizard.scss#L513-L533

2024-05-16 12:23 UTC, thatblindgeye commented
@mcoker Updated, but just to note In React, a consumer would still be able to create a custom footer that doesn't use ActionList (see [custom footer example](https://www.patternfly.org/components/wizard#custom-footer)). In those scenarios, I assume we'd just recommend either using Action List or utilizing our flex layouts?

2024-05-16 15:27 UTC, mcoker approved these changes
🥳🍕

2024-05-16 15:28 UTC, merged