chore(datalist): reduce mobile borders to 2px
patternfly/patternfly pull request #6615
Opened 2024-05-03 17:36 UTC by evwilkin

This PR updates the default DataList and DataListItem borders from `--pf-t--global--spacer--sm` to `--pf-t--global--border--width--200`

2024-05-03 17:39 UTC, patternfly-build commented
Preview: https://patternfly-pr-6615.surge.sh

2024-05-08 00:10 UTC, mcoker requested changes
Looks like there is a semantic token that fits the bill here https://github.com/patternfly/patternfly/blob/7f440dae1fb83b5ceb178c738a15425849b5503e/src/patternfly/base/tokens/tokens-default.scss#L209

The `--[100-900]` (or whatever the range is) tokens are what we refer to as "base" tokens (similar to [color palette vars](https://github.com/patternfly/patternfly/blob/v6/src/patternfly/base/tokens/tokens-palette.scss)) and in general we try to avoid using them unless there is no other/more appropriate semantic variable available.

2024-05-08 00:10 UTC, mcoker commented on src/patternfly/components/DataList/data-list.scss
> +  --#{$data-list}--BorderBlockStartWidth: var(--pf-t--global--border--width--200);
```suggestion
  --#{$data-list}--BorderBlockStartWidth: var(--pf-t--global--border--width--strong);
```

2024-05-08 00:10 UTC, mcoker commented on src/patternfly/components/DataList/data-list.scss
> +  --#{$data-list}__item--BorderBlockEndWidth: var(--pf-t--global--border--width--200);
```suggestion
  --#{$data-list}__item--BorderBlockEndWidth: var(--pf-t--global--border--width--strong);
```

2024-05-08 15:14 UTC, mcoker approved these changes
L🍕TM!!

2024-05-08 15:28 UTC, kaylachumley approved these changes
looks great! thanks!

2024-05-08 15:28 UTC, merged

2024-05-08 19:04 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.124 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.124)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.124)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: