fix(chip): removed chip, chip group, references
patternfly/patternfly pull request #6638
Opened 2024-05-09 20:39 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/6620

2024-05-09 20:42 UTC, patternfly-build commented
Preview: https://patternfly-pr-6638.surge.sh

2024-05-10 12:48 UTC, thatblindgeye requested changes

2024-05-10 12:48 UTC, thatblindgeye commented on src/patternfly/demos/Toolbar/examples/Toolbar.md
> +        {{#> toolbar-item toolbar-item--modifier=(concat 'pf-m-label-group ' toolbar-item-label-group--modifier)}}
Doesn't look like there are any styles for a label group modifier on a toolbar item.

2024-05-10 12:48 UTC, thatblindgeye commented on src/patternfly/components/Toolbar/toolbar.scss
> +.#{$toolbar}__group.pf-m-label-group-container,
Wouldn't this conflict with line 235, since they're both targeting a `.toolbar-group.label-group-container` selector?

2024-05-10 12:48 UTC, thatblindgeye commented on src/patternfly/demos/Toolbar/examples/Toolbar.md
> +    {{#> toolbar-item toolbar-item--modifier=(concat 'pf-m-label-group ' toolbar-item-label-group--modifier)}}
Similar to above, we don't have styles for these combinations of selectors, do we want to keep them on?

2024-05-10 12:48 UTC, thatblindgeye commented on src/patternfly/components/Toolbar/examples/Toolbar.md
> +| `.pf-m-label-container` | `.pf-v6-c-toolbar__content-section`, `.pf-v6-c-toolbar__group` | Modifies the toolbar element for applied filters layout. |
Should be label-group-container. Looks like we're also missing documentation on just `pf-m-label-group`

2024-05-10 19:50 UTC, thatblindgeye approved these changes
Since the above are pre-existing I'd be good with them being addressed in a followup. Other than that and merge conflict lgtm

2024-05-10 19:52 UTC, mcoker commented
@thatblindgeye great callouts! Created a follow up for that work since my main goal for this PR is to remove the chip styles so react doesn't parse them when pulling in core. Follow up issue - https://github.com/patternfly/patternfly/issues/6645

2024-05-10 20:01 UTC, merged

2024-05-10 20:01 UTC, mcoker commented
@kmcfaul @srambach - went ahead and merged this since removing the stylesheets unblocks other issues, but feel free to review when you get a chance and we can create follow ups for anything you find.

2024-05-10 20:08 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.130 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.130)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.130)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: