fix(table): updated thead td to th
patternfly/patternfly pull request #6689
Opened 2024-05-23 18:07 UTC by mattnolting

closes #6272 

This PR creates a container partial container for special table cells. The internals of the modifiers partials remain unchanged while the wrapping element detects `IsThead` and return `th` if true, `td` if false. Empty cells default screen reader text is set to "Action" (the most common use case) and optionally updated text via `table-cell--text`.

2024-05-23 18:09 UTC, patternfly-build commented
Preview: https://patternfly-pr-6689.surge.sh

2024-06-05 13:23 UTC, thatblindgeye requested changes

2024-06-05 13:23 UTC, thatblindgeye commented on src/patternfly/components/Table/examples/Table.md
> +      {{> table-cell-empty table-cell--text='Radio select'}}
Not really a blocker, just depends how strict we want to be about parity between Core and React examples. React uses "Row select" and similar verbiage for these types of empty cells.

2024-06-05 13:23 UTC, thatblindgeye commented on src/patternfly/components/Table/TableCells/table-cell.hbs
> +</{{table-cell--tag}}>
We also need to be able to add an aria-label to the `th` element, in instances where there is visible content but no visible text content (checkbox, plain icon button, etc). The checkbox example in React has `<th aria-label="Row select" ....`, while the checkbox inside the th has its own aria-label to denote the action.

Core examples that would need an aria-label on the outer `th` element:

- Checkboxes and actions example
- Expandable example (both the "toggle all" button and "select all" checkbox)
- Expandable with set width columns example
- Expandable with nested table example (from what I can tell, the aria-labelledby on the "toggle all rows" button could be removed as it's not pointing to anything valid/doesn't need to. The aria-labelledby on the individual row toggles could be removed and the aria-label updated to e.g. "Toggle row 1", or the aria-labelledby needs to point to a valid element as they currently do not. This isn't a blocker for this PR, though)
- Compact example
- Compact expandable example
- Clickable example
- Clickable and expandable example
- Borderless example
- Borderless compact example
- Borderless expandable example
- Width modifiers examples
- Nested column headers and expandable rows
- Favorites examples
- Favorites sortable example (would also apply to your other PR for favorite sortable)
- Striped expandable table example

2024-06-10 14:01 UTC, mattnolting commented on src/patternfly/components/Table/TableCells/table-cell.hbs
> +{{#> config table-cell--tag=(ternary IsThead 'th' 'td')}}
`config` is a wrapping agent with no corresponding `.hbs` partial.  `table-thead.hbs` and `table-tbody.hbs` assign [`IsThead`](https://github.com/patternfly/patternfly/blob/v6/src/patternfly/components/Table/table-thead.hbs#L3) and [`IsTbody`](https://github.com/patternfly/patternfly/blob/1f6e12340d166db38e994e5e62de002f3d795f7f/src/patternfly/components/Table/table-tbody.hbs#L3) respectively.

```
{{#>
  configd
  IsBody=true
}}````

2024-07-24 12:11 UTC, thatblindgeye approved these changes

2024-08-13 17:47 UTC, mcoker commented
Attaching the backstop report - [BackstopJS Report.pdf](https://github.com/user-attachments/files/16603370/BackstopJS.Report.pdf)

Looks like there may at least be an issue with icons rendering in menu toggles. Here's a toolbar example that's rendering an empty toggle

<img width="888" alt="Screenshot 2024-08-13 at 12 45 20 PM" src="https://github.com/user-attachments/assets/3c76def5-3e27-4722-976b-d0b03b8950bc">

2024-08-20 00:04 UTC, mcoker commented
@thatblindgeye would you mind reviewing this again? Particularly with the last changeset - https://github.com/patternfly/patternfly/pull/6689/commits/68bd944fad9251671371240be84c270627566bba

2024-08-20 00:50 UTC, mcoker reviewed
Left a couple of comments and attaching the backstop report: 
[table-8.19.24.pdf](https://github.com/user-attachments/files/16667212/table-8.19.24.pdf)

Mostly it looks like these two things:
* column widths changed (even when there are no empty headers, actions, or truncated test)
* some `<th>` cells are no longer truncated by default

Are those to be expected?

If there are more updates, would you mind attaching visual regressions and leave a comment explaining the errors?

2024-08-20 00:50 UTC, mcoker commented on src/patternfly/components/Table/table.scss
> +  &.#{$table}__thead {
This compiles to

```
.pf-v6-c-table :where([class*=pf-v6-c-table]),
:where(.pf-v6-c-table) > :is(thead, tbody),
.pf-v6-c-table.pf-v6-c-table__thead
```

Just want to verify that's correct - particularly the last line? Curious when we have `.pf-v6-c-table.pf-v6-c-table__thead` if so.

2024-08-20 00:50 UTC, mcoker commented on src/patternfly/demos/Toolbar/toolbar-template.hbs
> +          {{> toolbar-toggle menu-toggle-icon='filter'}}
Did you mean to leave this in?

```suggestion
          {{> toolbar-toggle}}
```

2024-08-26 13:14 UTC, thatblindgeye reviewed
Other than the a11y failures this looks good

2024-08-27 17:18 UTC, thatblindgeye approved these changes

2024-08-27 18:35 UTC, mcoker reviewed
@mattnolting LGTM, just want to confirm the changes in the backstop report are good. 
[BackstopJS Report.pdf](https://github.com/user-attachments/files/16767349/BackstopJS.Report.pdf)

Particularly this change on the [sortable favorites table example](https://patternfly-pr-6689.surge.sh/components/table/html/favorites-sortable-example/) which changes the favorite button from a sorted state to not

<img width="592" alt="Screenshot 2024-08-27 at 1 30 36 PM" src="https://github.com/user-attachments/assets/2a7b46d9-f092-4072-b3cf-d1f92a5695a1">

2024-08-27 18:44 UTC, mcoker commented on src/patternfly/components/Table/table.scss
> -  }
Just want to make sure this is intentional? If so can you give a summary of why? Looks like we'll need a react update for this, too.

2024-08-29 14:31 UTC, mcoker commented on src/patternfly/components/Table/table.scss
>  }
```suggestion

  &.pf-m-border-row {
    border-block-end: var(--#{$table}--border-width--base) solid var(--#{$table}--BorderColor);
  }
}
```

2024-08-29 15:27 UTC, mcoker approved these changes
🎃👍

2024-08-29 15:27 UTC, merged

2024-08-29 15:35 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.227 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.227)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.227)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: