feat(TextInputGroup): added validation
patternfly/patternfly pull request #6802
Opened 2024-06-17 15:58 UTC by thatblindgeye

Closes #6654

2024-06-17 16:01 UTC, patternfly-build commented
Preview: https://patternfly-pr-6802.surge.sh

2024-06-26 12:27 UTC, andrew-ronaldson approved these changes
This looks good to me. One unrelated nit is that we talked about moving the X button to flex-start instead of center. Could we squeeze that in or make its own issue

<img width="851" alt="Screenshot 2024-06-26 at 9 25 24 AM" src="https://github.com/patternfly/patternfly/assets/28658548/af2d7c87-081b-4000-92b6-647dde778fa5">

2024-06-26 17:19 UTC, mcoker commented
@thatblindgeye if you rebase this PR, the a11y errors should go away since we removed the context selector component.

2024-06-26 22:29 UTC, mcoker commented
@thatblindgeye @andrew-ronaldson do we want badges and other actions in the utilities element to be centered vertically all the time for both single-line and multi-line text input group layouts? Or should everything be vertically centered in a single-line text input group, but be start aligned (vertically centered with the first line of content) in a mult-line text input group?

2024-06-27 15:31 UTC, andrew-ronaldson commented
If the children of the utilities container were aligned to top would we need extra margin around the badge to make it visually centered with the X button. 
![Screenshot 2024-06-27 at 11 14 54 AM](https://github.com/patternfly/patternfly/assets/28658548/b6921b8e-88fe-4162-a97d-ab7dfb31675c)

2024-07-02 19:31 UTC, mattnolting requested changes
Great work @thatblindgeye! Only thing I'm noticing is icon positioning. Following comments will address. 

**Before:**

![Screenshot 2024-07-02 at 3 31 06 PM](https://github.com/patternfly/patternfly/assets/5385435/d51cc9d5-1d76-4b1d-baeb-27ca3266408f)

**Update:**

![Screenshot 2024-07-02 at 3 30 50 PM](https://github.com/patternfly/patternfly/assets/5385435/8f33b90f-a3e1-453b-8c4d-cd81cbe3dfd8)

2024-07-02 19:31 UTC, mattnolting commented on src/patternfly/components/TextInputGroup/text-input-group-template-status.hbs
> +{{/if}}
```suggestion
{{/if}}

```

2024-07-02 19:31 UTC, mattnolting commented on src/patternfly/components/TextInputGroup/text-input-group.scss
>    }
```suggestion

    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: calc(var(--#{$text-input-group}__LineHeight) * --#{$text-input-group}__FontSize));
  }
```

2024-07-02 19:31 UTC, mattnolting commented on src/patternfly/components/TextInputGroup/text-input-group.scss
>    }
Add these to `:where(:root)`

```
  --#{$text-input-group}__LineHeight): var(--pf-t--global--font--line-height--body);
  --#{$text-input-group}__FontSize: var(--pf-t--global--font--size--body--default);
```

2024-07-02 19:31 UTC, mattnolting commented on src/patternfly/components/TextInputGroup/text-input-group.scss
>    }
Add these to `.#{$text-input-group}`

```
  line-height: var(--#{$text-input-group}__LineHeight);
  font-size: var(--#{$text-input-group}__FontSize);
```

2024-07-02 19:32 UTC, mcoker requested changes
Looks fantastic. I left some comments and am also curious about a couple of things:
* We're drawing the border on the outer text input group wrapper from  the child `__main` element. That works now, but if we need to add `position: relative` to `__main`, we'll no longer be able to create the border from `__main`. Can we move both the status modifiers and the visible border to the outer `.pf-v6-c-text-input-group` element?
* What's the role of `.pf-m-status`? One thing is I see we're adding selectors like `.thing:where(.pf-m-success, .pf-m-error, ...)`... we could require `.pf-m-status` to be used with any kind of status on an element like `class="pf-m-status pf-m-error"`, and then instead of listing all of the classes in our selector, we could just target `.pf-m-status`.

2024-07-02 19:32 UTC, mcoker commented on src/patternfly/components/TextInputGroup/text-input-group.scss
> +    --#{$text-input-group}__icon--m-status--Color: var(--#{$text-input-group}--m-disabled--Color);
We should probably update these to use the disabled icon color token

2024-07-09 17:41 UTC, andrew-ronaldson commented
Changes look good Eric! I will close the related issue for the border-radius

2024-07-09 20:27 UTC, mcoker approved these changes
🐳

2024-07-09 20:30 UTC, merged

2024-07-09 20:38 UTC, patternfly-build commented
:tada: This PR is included in version 6.0.0-alpha.184 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.184)
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.0.0-alpha.184)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: