fix(table-text): updated truncate value
patternfly/patternfly pull request #7175
Opened 2024-10-24 17:01 UTC by mattnolting

fixes #7172 

# TLDR:
`max(var(--#{$table}--m-truncate__text--MinWidth), var(--#{$table}--m-truncate--cell--MaxWidth));` sets `table__text.m-truncate` to accept larger of the two values, assuring that truncated text is always at least `5ch` long and at max `100%`.

2024-10-24 17:03 UTC, patternfly-build commented
Preview: https://patternfly-pr-7175.surge.sh

2024-11-06 14:46 UTC, nicolethoen approved these changes

2024-11-06 20:58 UTC, mcoker requested changes
Doesn't appear to be working in the preview? 
<img width="1506" alt="Screenshot 2024-11-06 at 2 53 49 PM" src="https://github.com/user-attachments/assets/3bfcdc4f-48af-47cf-a1dd-299ec549b7d5">

<img width="1179" alt="Screenshot 2024-11-06 at 2 52 33 PM" src="https://github.com/user-attachments/assets/81c1afe2-6b05-49ad-a32d-67b14c11e767">

2024-11-21 20:30 UTC, srambach approved these changes
Looks like it's working as expected now.

2024-11-21 22:11 UTC, merged

2024-11-21 22:19 UTC, patternfly-build commented
:tada: This PR is included in version 6.1.0-prerelease.6 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.1.0-prerelease.6)
- [npm package (@prerelease dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.1.0-prerelease.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: