chore(tile): mark tile as deprecated
patternfly/patternfly pull request #7178
Opened 2024-10-24 20:33 UTC by mcoker

fixes https://github.com/patternfly/patternfly/issues/7177

2024-10-24 20:36 UTC, patternfly-build commented
Preview: https://patternfly-pr-7178.surge.sh

2024-10-24 21:00 UTC, tlabaj approved these changes

2024-10-25 15:24 UTC, evwilkin requested changes
To work as intended we'll want to move this file into a `deprecated` directory at `/components/Tile/deprecated/`

[Current logic in the documentation-site](https://github.com/patternfly/patternfly-org/blob/main/packages/documentation-site/patternfly-docs/patternfly-docs.source.js#L67-L71) looks for Core examples within a `deprecated` directory, similar to how ApplicationLauncher was in v5:
- https://github.com/patternfly/patternfly/tree/v5/src/patternfly/components/AppLauncher/deprecated

This changes the tab name to "HTML-deprecated" and unblocks the "deprecated" label in the sidenav [when not combined with a "React" or "Core" tab](https://github.com/patternfly/patternfly-org/blob/main/packages/documentation-framework/components/sideNav/sideNav.js#L94-L95) (in the case that a deprecated implementation also has a newer implementation documented). 

FYI - The frontmatter here will enable the deprecation alert at the top of the Core docs page.

2024-10-25 16:08 UTC, mcoker commented
@evwilkin ah hah, thanks!! Updated - https://patternfly-pr-7178.surge.sh/components/tile

2024-10-25 16:15 UTC, evwilkin approved these changes
🍕

2024-10-30 15:58 UTC, merged

2024-10-30 16:22 UTC, patternfly-build commented
:tada: This PR is included in version 6.1.0-prerelease.1 :tada:

The release is available on:
- [GitHub release](https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.1.0-prerelease.1)
- [npm package (@prerelease dist-tag)](https://www.npmjs.com/package/@patternfly/patternfly/v/6.1.0-prerelease.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: